specify Not_Found err handling
DeFiCh/whale pull request #135
Opened 2021-06-02 07:46 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #99

2021-06-05 15:23 UTC, fuxingloh requested changes
thanks for the refactoring!!! 

Some comments:

1. We can use `lodash` for utilities so we don't need to maintain them. 
2. There are some `throw error` tests with missing `throw new Error('do not reach here')` but I was thinking maybe adding `expect.assertions(2)` would be cleaner

2021-06-05 15:23 UTC, fuxingloh commented on src/module.api/shared/utils.ts
> +export function grabValueByKey (obj: any, key: string): any {
We can remove shared/utils with `lodash`.

1. https://lodash.com/docs/4.17.15#get
2. https://lodash.com/docs/4.17.15#isObject

2021-06-05 15:23 UTC, fuxingloh commented on src/module.api/transaction.controller.spec.ts
> +      const hex = await createSignedTxnHex(container, 10, 9)
missing `throw` or  `expect.assertions(2)` here

2021-06-05 15:24 UTC, fuxingloh commented on src/module.api/shared/utils.ts
> +export function grabValueByKey (obj: any, key: string): any {
May packages already import them, we can import them also.

2021-06-06 09:27 UTC, canonbrother commented on src/module.api/shared/utils.ts
> +export function grabValueByKey (obj: any, key: string): any {
removed

2021-06-06 09:29 UTC, canonbrother commented on src/module.api/shared/utils.ts
> +export function grabValueByKey (obj: any, key: string): any {
ohh.. just noted that the `lodash` is a rich js utilities lib.

previously the purpose i created the `grabValueByKey` was to easily get the value by vary position of key (nested)
grabValueByKey(e, 'message')
```
e.message
e.payload.message
```
hmm... i think i'm a bit over-engineered, so straight away get the value will do.

2021-06-06 16:26 UTC, fuxingloh requested changes

2021-06-06 16:26 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +    } catch (err) {
```suggestion
    expect.assertions(2)
    try {
      await client.poolpair.get('A-B')
    } catch (err) {
```

With `expect.assertions` you don't need `throw new Error` since it does the same thing. I think using expect.assertions is clean when doing try catch test assertions. Since `throw new Error` is kind of anomalous.

2021-06-07 03:15 UTC, fuxingloh approved these changes

2021-06-07 03:15 UTC, merged