added cache prefix
DeFiCh/whale pull request #137
Opened 2021-06-07 04:48 UTC by canonbrother

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:
To categorize the cache for easier to differentiate cache id by prefix and prevent get overwritten by others

#### Which issue(s) does this PR fixes?:

Fixes #82

2021-06-07 05:04 UTC, fuxingloh commented
@canonbrother take a look at this, https://github.com/DeFiCh/whale/commit/87e7b46f0019ca874e435d6445641621ab9dd0b7

2021-06-07 06:27 UTC, canonbrother commented
> @canonbrother take a look at this, [87e7b46](https://github.com/DeFiCh/whale/commit/87e7b46f0019ca874e435d6445641621ab9dd0b7)
> 
> I think we should do something like this.

I see... yea noted!!

2021-06-10 08:40 UTC, fuxingloh commented on src/module.api/cache/global.cache.ts
> +    return await this.cacheManager.get<T>(key)
Since there is only one global cache, you can get the same instance via `module.get<Cache>(Cache)`.

2021-06-10 08:44 UTC, fuxingloh requested changes

2021-06-10 08:44 UTC, fuxingloh commented on src/module.api/cache/defid.cache.spec.ts
> +
I am curious about cache miss behavior I think we need coverage for that. Codecov is reporting that we don't have test for that scenario also.

2021-06-10 08:44 UTC, fuxingloh commented on src/module.api/cache/defid.cache.spec.ts
> +    const module = await Test.createTestingModule({
make this global

2021-06-10 08:44 UTC, fuxingloh commented on src/module.api/cache/defid.cache.spec.ts
> +    const abPoolPair = await cache.testGet<PoolPairInfo>(abKey)
```suggestion
    const cache = module.get<Cache>(Cache)
    const abPoolPair = await cache.get<PoolPairInfo>(abKey)
```

Should be able to return to do this.

2021-06-11 03:48 UTC, canonbrother commented on src/module.api/cache/defid.cache.spec.ts
> +
the result after killed the rpc and cache reset
```
try {
      await defiCache.getPoolPairInfo('4')
} catch (err) {
      expect(err.code).toStrictEqual('ECONNREFUSED')
      expect(err.type).toStrictEqual('system')
}
```

2021-06-11 03:54 UTC, canonbrother commented on src/module.api/cache/defid.cache.spec.ts
> +
hmm... wondering how to test this sanity check? 
it will get undefined only while blockchain output undefined
properly need to mock and hard return undefined
currently i skip it first
```
const result = await this.rpcClient.poolpair.getPoolPair(id)
/* istanbul ignore if  */
if (result[id] === undefined) {
    return undefined
}
```

2021-06-14 04:17 UTC, fuxingloh requested changes
some suggestions for review

2021-06-14 04:17 UTC, fuxingloh commented on src/module.api/cache/defid.cache.ts
> +    return result[id]
I think there are too many if conditions, creating too many logical branches.

We should make fetchPoolPairInfo return `PoolPairInfo | undefined`, for errors like "Unable to find poolpair" we can catch it here and return undefined. We can ignore other errors and escalate. This will simplify the consumer side, making it easier for them to consume the cache without worrying about error handling.

@canonbrother what do you think? I think this will cut down how deep our vertical codes get

```diff
-    try {
      const info = await this.deFiDCache.getPoolPairInfo(id)
      if (info === undefined) {
+        throw new NotFoundException('Unable to find poolpair')
      }
      return mapPoolPair(String(id), info)
-    } catch (e) {
-      /* istanbul ignore else */
-      if (e?.payload?.message === 'Pool not found') {
-        throw new NotFoundException('Unable to find poolpair')
-      } else {
-        throw new BadRequestException(e)
-      }
-    }
```

2021-06-14 05:18 UTC, canonbrother commented on src/module.api/cache/defid.cache.ts
> +    return result[id]
hmm.. 
```
const info = await this.deFiDCache.getPoolPairInfo(id)
if (info === undefined) { // <-- this is not reachable as rpc will throw error beforehand
   throw new NotFoundException('Unable to find poolpair')
}
 ```

2021-06-14 05:53 UTC, fuxingloh commented on src/module.api/cache/defid.cache.ts
> +    return result[id]
My thoughts are we keep the "expected returns" (errors included) within the cache. Meaning we catch the errors within the cache so that we return undefined if "Unable to find poolpair" are raised from defid-cache. As not found is an expected error, this makes it easier to consume the defid-cache without having to handle all the expected/unexpected errors.

2021-06-14 09:02 UTC, canonbrother commented on src/module.api/cache/defid.cache.ts
> +    return result[id]
yea done.. i refactored it by following
1. [deficache] try.. catch on exactly rpc call.. if err return undefined
2. [controller] if undefined throw err

2021-06-14 17:55 UTC, fuxingloh requested changes

2021-06-14 17:55 UTC, fuxingloh commented on src/module.api/cache/defid.cache.ts
> +    } catch (err) {
you still need to escalate non NotFound exception in defid.cache.ts

2021-06-15 04:09 UTC, fuxingloh requested changes

2021-06-15 04:09 UTC, fuxingloh commented on src/module.api/cache/defid.cache.ts
> +      }
```suggestion
      if (err?.payload?.message === 'Pool not found') {
        return undefined
      } else {
        throw err
      }
```

2021-06-15 04:09 UTC, fuxingloh commented on src/module.api/cache/defid.cache.ts
> +      }
```suggestion
      if (err?.payload?.message === 'Token not found') {
        return undefined
      } else {
        throw err
      }
```

2021-06-15 05:19 UTC, canonbrother commented on src/module.api/cache/defid.cache.ts
> +      }
phew.. got it!!

2021-06-15 06:47 UTC, fuxingloh approved these changes

2021-06-15 06:51 UTC, merged