Added BlockController and getBlockTip method
DeFiCh/whale pull request #188
Opened 2021-06-28 09:16 UTC by aikchun

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes part of #4 

#### Additional comments?:
Changes for
```
GET v1/:network/block/:id
GET v1/:network/block/:id/transactions
```
will be added in a separate PR.

2021-06-29 03:47 UTC, fuxingloh requested changes

2021-06-29 03:47 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +@Controller('/v1/:network/block')
it's v0 now

```suggestion
@Controller('/v0/:network/block')
```
```suggestion
@Controller('/v1/:network/block')
```

2021-06-29 03:47 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +  }
don't need to use defid semantic

The block list operation should always be sorted in descending order hence `/blocks size = 1` should give you the same result.

2021-06-29 03:47 UTC, fuxingloh commented on src/module.api/block.controller.spec.ts
> +  const defidUrl = await container.getCachedRpcUrl()
you should use e2e tests instead of spec.ts

it will be increasingly difficult to maintain spec for this scenario since you need to populate your own data.
Your own populated data is will break when upstream block model changed.

2021-06-29 04:51 UTC, aikchun commented on src/module.api/block.controller.ts
> +  }
What do you mean by `defid semantic`?

2021-06-29 07:51 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +  }
`getchaintips`, `tip` is a semantic of defid/bitcoind for whale since it's an indexer, it will index the best chain. You can just provide a normal RESTful design.

2021-07-01 13:00 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +
```suggestion

  @Get()
  async listBlocks(): Promise<...> {
    // pagination query block sort by latest
  }

```

2021-07-02 08:48 UTC, aikchun commented on src/module.api/block.controller.ts
> +
I have made changes for this.

2021-07-02 08:49 UTC, aikchun commented on src/module.api/block.controller.ts
> +  }
This means we won't need the api endpoints for this?

2021-07-03 07:03 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +  it('getBlockTransactions should get transactions from a block by hash', async () => {
Add test units to test negative flows => 
1) should throw error while getting non-existent hash
2) should listBlocks with an empty object if size ? next ? which is out of range

2021-07-04 08:08 UTC, fuxingloh requested changes

2021-07-04 08:08 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +  }
remove

2021-07-04 08:08 UTC, fuxingloh commented on src/module.model/block.ts
> +  async queryByHeight (limit: number, lt?: ModelKey): Promise<Block[]> {
revert, only number is allowed for each key

2021-07-08 00:53 UTC, aikchun commented on src/module.api/block.controller.ts
> +@Controller('/v0/:network/block')
Made changes for this.

2021-07-08 00:53 UTC, aikchun commented on src/module.api/block.controller.ts
> +  }
Made changes for this.

2021-07-08 00:54 UTC, aikchun commented on src/module.api/block.controller.ts
> +  }
Removed

2021-07-08 00:54 UTC, aikchun commented on src/module.model/block.ts
> +  async queryByHeight (limit: number, lt?: ModelKey): Promise<Block[]> {
Made changes.

2021-07-08 06:55 UTC, fuxingloh requested changes

2021-07-08 06:55 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    // id is not a number
```suggestion
```

2021-07-08 06:55 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    const transactions = await this.transactionMapper.queryByBlockHash(hash, query.size, query.next)
should support query by height and number as well

2021-07-08 06:55 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +}
```suggestion
function isHeight (str: string): boolean {
  return /^[0-9]+$/.test(str)
}
```

no negative number and you should call it is height

2021-07-08 06:55 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    const idIsNumber = isNumber(id)
don't declare const that you don't plan to reuse

2021-07-08 06:55 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    })
structure this like how you others are structured, there shouldn't be an `if` statement

https://github.com/DeFiCh/whale/blob/1d3a4268be91c16d13a9955879e0ac43836fad8a/src/module.api/address.controller.ts#L86-L90

2021-07-09 02:31 UTC, aikchun commented on src/module.api/block.controller.ts
> +    })
This `if` statement comes from the fact that `queryByHeight` requires a `number` for the second argument.

`query.next` is an optional string property which `parseInt` won't accept unless type guard is being applied.

Previously, I changed parameter type of the second argument to `ModelKey` from `number` to avoid this `if` statement [here](https://github.com/DeFiCh/whale/pull/188#discussion_r663465087)

Could you advise?

2021-07-09 07:22 UTC, aikchun commented on src/module.api/block.controller.ts
> +}
Made changes.

2021-07-09 07:22 UTC, aikchun commented on src/module.api/block.controller.ts
> +    const idIsNumber = isNumber(id)
Removed the variable.

2021-07-09 07:35 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +  it('getBlockTransactions should get transactions from a block by hash', async () => {
Added tests as suggested.

2021-07-09 07:45 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    })
Check these out, do read them in full at the source:

https://github.com/DeFiCh/whale/blob/e0422e76a9796a068f7ebcc2ba8d3c0358c1ff4d/src/module.api/_core/api.paged.response.ts#L38-L40

https://github.com/DeFiCh/whale/blob/e0422e76a9796a068f7ebcc2ba8d3c0358c1ff4d/src/module.api/_core/api.paged.response.ts#L58-L60

2021-07-09 08:06 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +    return await this.blockMapper.getByHash(id)
```suggestion
export function parseHeight (str?: string): number | undefined {
  if (str !== undefined && /^\d+$/.test(str)) {
    return parseInt(str)
  }
}

@Controller('/v0/:network/blocks')
export class BlockController {
  constructor (
    protected readonly blockMapper: BlockMapper,
    protected readonly transactionMapper: TransactionMapper
  ) {
  }

  @Get('')
  async listBlocks (
    @Query() query: PaginationQuery
  ): Promise<ApiPagedResponse<Block>> {
    const next: number | undefined = parseHeight(query.next)
    const blocks = await this.blockMapper.queryByHeight(query.size, next)

    return ApiPagedResponse.of(blocks, query.size, item => {
      return item.id
    })
  }

  @Get('/:id')
  async getBlock (@Param('id') id: string): Promise<Block | undefined> {
    const height = parseHeight(id)
    if (height !== undefined) {
      return await this.blockMapper.getByHeight(height)
    }

    // id is not a number
    return await this.blockMapper.getByHash(id)
```

2021-07-14 08:57 UTC, canonbrother commented on src/module.api/block.controller.ts
> +  async listBlocks (
```suggestion
  async list (
```

2021-07-14 08:59 UTC, canonbrother commented on src/module.api/block.controller.ts
> +  async getBlock (@Param('id') id: string): Promise<Block | undefined> {
`getBlock` -> `get`

2021-07-14 08:59 UTC, canonbrother commented on src/module.api/block.controller.ts
> +  async getBlock (@Param('id') id: string): Promise<Block | undefined> {
```suggestion
  async get (@Param('id') id: string): Promise<Block | undefined> {
```

2021-07-14 09:06 UTC, canonbrother commented on src/module.api/block.controller.e2e.ts
> +  })
duplicated

2021-07-14 09:14 UTC, canonbrother commented on src/module.api/block.controller.e2e.ts
> +  it('getBlockTransactions should get transactions from a block by hash', async () => {
consistency wise, can you follow our test pattern?
eg:
https://github.com/DeFiCh/whale/blob/main/src/module.api/poolpair.controller.e2e.ts

2021-07-14 09:19 UTC, canonbrother requested changes
take note on code consistency

2021-07-15 07:50 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +  })
Changed the test to input `undefined` in the argument

2021-07-15 07:51 UTC, aikchun commented on src/module.api/block.controller.ts
> +  async listBlocks (
Made these changes.

2021-07-15 09:55 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    expect(paginatedTransactions.data.length).toStrictEqual(1)
If there is only 1 transaction, we do not know whether the pagination will work or not.
Could you figure out how to increase the number of transactions?

2021-07-15 09:57 UTC, jingyi2811 commented
You shouldn't commit and push `package-lock.json`

2021-07-15 10:09 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedTransactions = await controller.getBlockTransactions('100', { size: 30, next: '10' })
Could we assume `getBlockTransactions` always return 0 or 1 record? 
If yes, you shouldn't add a pagination feature to `getBlockTransactions`
If no, you should think of a way to improve the test so `paginatedTransactions.data.length` returns more than 1 record. With more than 1 record, then only we can know whether the pagination can work or not.

2021-07-15 10:20 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    expect(paginatedBlocks.data.length).toStrictEqual(30)
Write something like this to test whether pagination is working correctly or not

```
 const first = await controller.list({ size: 2 })

    expect(first.data.length).toStrictEqual(2)
    expect(first.page?.next).toStrictEqual('1')

    expect(first.data[0]).toStrictEqual(expect.objectContaining({ id: '0', symbol: 'DFI', symbolKey: 'DFI' }))
    expect(first.data[1]).toStrictEqual(expect.objectContaining({ id: '1', symbol: 'DBTC', symbolKey: 'DBTC' }))

    const next = await controller.list({
      size: 2,
      next: first.page?.next
    })

    expect(next.data.length).toStrictEqual(2)
    expect(next.page?.next).toStrictEqual('3')

    expect(next.data[0]).toStrictEqual(expect.objectContaining({ id: '2', symbol: 'DETH', symbolKey: 'DETH' }))
    expect(next.data[1]).toStrictEqual(expect.objectContaining({ id: '3', symbol: 'DBTC-DET', symbolKey: 'DBTC-DET' }))

    const last = await controller.list({
      size: 1,
      next: next.page?.next
    })

    expect(last.data.length).toStrictEqual(0)
    expect(last.page).toBeUndefined()
```

2021-07-16 07:06 UTC, fuxingloh commented
missing `whale-api-client` changes

2021-07-19 07:54 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    const paginatedTransactions = await controller.getBlockTransactions('100', { size: 30, next: '10' })
Unfortunately, I'm unable to deterministically generate a block with an arbitary set of transaction that I can test the pagination with.

This could be possible in the future with this https://github.com/DeFiCh/jellyfish/issues/294 and https://github.com/DeFiCh/jellyfish/pull/450.

Therefore may I suggest testing for the pagination for transactions be tested separately at a later date.

2021-07-19 07:56 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    expect(paginatedBlocks.data.length).toStrictEqual(30)
I have made changes based on this.

I used `height` as a determining factor as the list is sorted by height and should be paged as so.

2021-07-19 07:57 UTC, aikchun commented
> I think you shouldn't commit and push `package-lock.json`

@jingyi2811 I have reverted `package-lock.json`.

2021-07-19 14:38 UTC, jingyi2811 commented
> > I think you shouldn't commit and push `package-lock.json`
> 
> @jingyi2811 I have reverted `package-lock.json`.

Okat

2021-07-19 16:30 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +describe('parseHeight', () => {
We normally don't test the util function we create in whale.

2021-07-19 16:32 UTC, jingyi2811 commented on src/module.api/block.controller.ts
> +    const height = parseHeight(query.next)
Try something like this `const height = query.next? parseInt(query.next): undefined`
I think it offers the same functionality as parseHeight.

2021-07-19 16:51 UTC, jingyi2811 commented
Cannonbrother mentioned `take note on code consistency`, which I agree too.
You probably may spend some time to read how the tests written by others

In general, you should only write 3 tests for function with pagination and 2 tests for function without pagination.

For example,

For list
- should list
- should list with pagination
- should list empty object as out of range

For get
- should get
- should throw error while getting non-existent token

For get with pagination
- should get
- should get with pagination
- should get empty object as out of range

The reason why we don't write test very detail in whale because we don't want to duplicate the test if it is already written in  the jellyfish.

2021-07-20 05:49 UTC, jingyi2811 commented
Design your test like this

```

  describe('list', () => {
  }

  describe('get', () => {
  }

  describe('getBlockTransactions', () => {
  }

```

2021-07-21 03:28 UTC, aikchun commented
> Design your test like this
> 
> ```
> 
>   describe('list', () => {
>   })
> 
>   describe('get', () => {
>   })
> 
>   describe('getBlockTransactions', () => {
>   })
> ```

@jingyi2811 I have restructured the tests to look like how it is structured in other tests.

Also I have re written the test to test pagination and removed some unnecessary test.

However, I didn't remove the tests for utility function as I feel like it makes less sense to make the codebase less tested.

2021-07-21 04:44 UTC, jingyi2811 commented
You push package-lock.json again

2021-07-21 07:37 UTC, fuxingloh requested changes

2021-07-21 07:37 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +        return ApiPagedResponse.of(await this.transactionMapper.queryByBlockHash(block.id, query.size, query.next), query.size, transaction => {
This converges into call `queryByBlockHash`, your code must converge

2021-07-21 07:37 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +      return item.id
```suggestion
      return item.height
```

2021-07-22 02:45 UTC, aikchun commented on src/module.api/block.controller.ts
> +      return item.id
Corrected this.

2021-07-22 02:45 UTC, aikchun commented on src/module.api/block.controller.ts
> +        return ApiPagedResponse.of(await this.transactionMapper.queryByBlockHash(block.id, query.size, query.next), query.size, transaction => {
Made changes to converge the code.

2021-07-22 02:45 UTC, aikchun commented
> You pushed package-lock.json again

I've reverted the changes properly this time. @jingyi2811

2021-07-22 05:59 UTC, fuxingloh commented
> missing `whale-api-client` changes

FYI you need to implement `whale-api-client` of the available endpoint you exposed.

2021-07-23 10:45 UTC, jingyi2811 commented on packages/whale-api-client/src/api/block.ts
> +  async getBlockTransactions (id: string, size = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
size: number = 30

2021-07-23 10:46 UTC, jingyi2811 commented on packages/whale-api-client/src/api/block.ts
> +  async getBlockTransactions (id: string, size = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
Like how you wrote in line 14

2021-07-23 12:51 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/block.test.ts
> +    await container.waitForWalletBalanceGTE(100)
I think you can move this line to 27.

2021-07-23 12:55 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/block.test.ts
> +  it('should getBlockTransactions through height', async () => {
Need to add negative scenarios too

For eg: what happen if you call `await client.block.getBlockTransactions('$*@')`

2021-07-23 12:59 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/block.test.ts
> +import { MasterNodeRegTestContainer } from '@defichain/testcontainers'
Can you arrange your test like this

 ```
 describe('list', () => {
  })

  describe('get', () => {
  })

  describe('getBlockTransactions', () => {
  })
```

Kindly refer to other test file in the same folder

2021-07-23 13:01 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/block.test.ts
> +    expect(second.length).toStrictEqual(30)
To verify pagination works correctly, we usually paginate 3 times

First, second and last

2021-07-25 19:22 UTC, fuxingloh requested changes

2021-07-25 19:22 UTC, fuxingloh commented on packages/whale-api-client/src/api/block.ts
> +  async getBlockTransactions (id: string, size: number = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
```suggestion
  async getTransactions (id: string, size: number = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
```

2021-07-25 19:22 UTC, fuxingloh commented on packages/whale-api-client/src/whale.api.client.ts
> +  public readonly block = new Blocks(this)
```suggestion
  public readonly blocks = new Blocks(this)
```

On second thought, I think to call it as `blocks` instead.

2021-07-26 02:08 UTC, aikchun commented on packages/whale-api-client/src/api/block.ts
> +  async getBlockTransactions (id: string, size: number = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
Fixed.

2021-07-26 02:08 UTC, aikchun commented on packages/whale-api-client/src/whale.api.client.ts
> +  public readonly block = new Blocks(this)
Fixed.

2021-07-26 02:08 UTC, aikchun commented on packages/whale-api-client/__tests__/api/block.test.ts
> +    expect(second.length).toStrictEqual(30)
Added assertion for the third and final page.

2021-07-26 02:09 UTC, aikchun commented on packages/whale-api-client/__tests__/api/block.test.ts
> +    expect(second.length).toStrictEqual(30)
Added assertion for the third and final page.

2021-07-26 02:09 UTC, aikchun commented on packages/whale-api-client/__tests__/api/block.test.ts
> +import { MasterNodeRegTestContainer } from '@defichain/testcontainers'
Restructured the tests in this way.

2021-07-26 02:10 UTC, aikchun commented on packages/whale-api-client/__tests__/api/block.test.ts
> +  it('should getBlockTransactions through height', async () => {
Added assertions for invalid input for `getTransactions` and `get`

2021-07-26 02:10 UTC, aikchun commented on packages/whale-api-client/__tests__/api/block.test.ts
> +    await container.waitForWalletBalanceGTE(100)
Made the changes.

2021-07-26 03:51 UTC, aikchun commented on packages/whale-api-client/src/api/block.ts
> +  async getBlockTransactions (id: string, size = 30, next?: string): Promise<ApiPagedResponse<Transaction>> {
Added type annotation for `size` parameter.

2021-07-26 05:11 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 100000, next: '100' })
Should fail if out of range

2021-07-26 05:11 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
Should fail if out of range

2021-07-26 05:21 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
Let say you have a list of objects => 9, 8, 7, 6, 5, 4, 3, 2, 1

list with next = 1  will give you error. Because there is no objects after it

2021-07-26 13:42 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 100000, next: '100' })
Why should this fail if the size is out of range?

It makes to sense to return all items if in a single page if the request page size is bigger is that data size.

By default, the size is 30, if for some reason, the chain has less than 30 blocks (or any other record for that matter), then we wouldn't return them any data?

Besides, it's part of the feature here https://github.com/DeFiCh/whale/blob/1d29ceeec4657e490f93a377bdf1cbe056216a01/src/module.api/poolpair.controller.e2e.ts#L88

2021-07-26 13:45 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
This shouldn't fail the request as we cannot assume that the client exactly how many blocks were already generated.

If `next` is too large we should return the first page so that the user is able to fetch the second page.

2021-07-26 13:47 UTC, aikchun commented
Added assertion for list block request when the `size` and `next` value are out of range.

2021-07-26 16:03 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
We add pagination feature to whale because we are unable to display every information in 1 page if the items are too many 

Let say there are 30 elements, and we want to display 10 in 1 page. There supposes to have 3 pages. 

1 ... 10, 11 ... 20, 21 ... 30

const first = await controller.list({ size: 10 }) will show 1 ... 10 elements
const second = await controller.list({ size: 10, next: 10 }) will show 11 ... 20 elements
const third = await controller.list({ size: 10, next: 20 }) will show 21 ... 30 elements
  
Next is always the last element of previous sublist

2021-07-26 16:05 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
Maybe you need to change the logic in `controller.list`

2021-07-26 16:14 UTC, jingyi2811 commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 100000, next: '100' })
I should write longer.`It makes to sense to return all items if in a single page if the request page size is bigger is that data size `=> This is correct.  When you search the word `out of range` in the project. You find this `it `

```
  it('should listTokens with an empty object if size 100 next 300 which is out of range', async () => {
    const result = await controller.list({ size: 100})

    expect(result.data.length).toStrictEqual(0)
    expect(result.page).toBeUndefined()
  })
```

Why don't you just copy the idea and combine your `size` and `next` tests into one?

2021-07-27 03:12 UTC, jingyi2811 commented
I think this may help you

For queryByHeight, where the result is sorted by desc,
your next value should be lesser compare to previous sublist 

 ```
async queryByHeight (limit: number, lt?: number): Promise<Block[]> {
    return await this.database.query(BlockMapping.index.height, {
      limit: limit,
      order: SortOrder.DESC,
      lt: lt
    })
  }
```

For queryByBlockHash, where the result is sorted by asc,
your next value should be greater compare to previous sublist 

 ```
 async queryByBlockHash (hash: string, limit: number, gt?: string): Promise<Transaction[]> {
    return await this.database.query(TransactionMapping.index.block_txid, {
      partitionKey: hash,
      limit: limit,
      order: SortOrder.ASC,
      gt: gt
    })
  }
```

2021-07-27 03:57 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 100000, next: '100' })
It doesn't make sense to copy this test.

1. By combining `size` and `next` being out of range, doesn't elucidate the conditions that cause `results.data.length` to be 0. By testing the params individually, it could be shown that `next` being out of range is the primary cause for `result.data.length` to be 0.
2. listToken is fetching the list i [lexicographic order](https://github.com/DeFiCh/ain/blob/87a4760e06d286edcd481b810200b0b480e17282/src/masternodes/rpc_accounts.cpp#L241), which is an ascending order of sorts which makes sense if `next` is out of range, you are paging outside any datta.

list blocks, however, I refer back to @fuxingloh [comment](https://github.com/DeFiCh/whale/pull/188#discussion_r660259027) will always be in `descending` order therefore it makes that we will always have data even if the value for `next` is more than max height of the blocks.

2021-07-27 04:01 UTC, aikchun commented
> I think this may help you. In your test
> 
> For queryByHeight, where the result is sorted by desc,
> your next value should be lesser compare to previous sublist
> 
> ```
> async queryByHeight (limit: number, lt?: number): Promise<Block[]> {
>    return await this.database.query(BlockMapping.index.height, {
>      limit: limit,
>      order: SortOrder.DESC,
>      lt: lt
>    })
>  }
> ```
> 
> For queryByBlockHash, where the result is sorted by asc,
> your next value should be greater compare to previous sublist
> 
> ```
> async queryByBlockHash (hash: string, limit: number, gt?: string): Promise<Transaction[]> {
>    return await this.database.query(TransactionMapping.index.block_txid, {
>      partitionKey: hash,
>      limit: limit,
>      order: SortOrder.ASC,
>      gt: gt
>    })
>  }
> ```

list block operation will always in [descending order](https://github.com/DeFiCh/whale/pull/188#discussion_r660259027)

2021-07-27 04:07 UTC, fuxingloh commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 100000, next: '100' })
Yeah @aikchun is right on this

2021-07-27 04:21 UTC, aikchun commented on src/module.api/block.controller.e2e.ts
> +    const paginatedBlocks = await controller.list({ size: 30, next: '100000' })
I have added tests to assertion for the length of data to be `0` when the `next` is `0` for both the controller and the `WhaleApiClient`.

2021-07-27 07:11 UTC, jingyi2811 commented on src/module.api/block.controller.ts
> +  async parseHeightAndGetBlock (str?: string): Promise<Block | undefined> {
`Str?` is optional. Can this be `str` ?

2021-07-27 07:12 UTC, jingyi2811 commented on src/module.api/block.controller.ts
> +    const transactions = await this.transactionMapper.queryByBlockHash((block != null) ? block.id : id, query.size, query.next)
Can this be `!== undefined`?

2021-07-27 07:47 UTC, aikchun commented on src/module.api/block.controller.ts
> +    const transactions = await this.transactionMapper.queryByBlockHash((block != null) ? block.id : id, query.size, query.next)
Made changes for this

2021-07-27 07:47 UTC, aikchun commented on src/module.api/block.controller.ts
> +  async parseHeightAndGetBlock (str?: string): Promise<Block | undefined> {
Made the changes for this.

2021-07-27 09:13 UTC, jingyi2811 approved these changes

2021-07-27 17:55 UTC, fuxingloh approved these changes

2021-07-27 18:06 UTC, merged