Index oracle weightage
DeFiCh/whale pull request #191
Opened 2021-06-29 10:45 UTC by jingyi2811

What kind of PR is this?:
/kind feature

What this PR does / why we need it:
Index oracle weightage

Which issue(s) does this PR fixes?:
Fixes #144

Additional comments?:

2021-06-29 10:49 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +        if (!vout.scriptPubKey.hex.startsWith('6a')) {
I guess all custom transactions start with 6a.

2021-06-29 10:50 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +  async invalidate (block: RawBlock): Promise<void> {
How to test this?

2021-06-29 10:50 UTC, jingyi2811 commented on src/module.model/oracle.weightage.ts
> +        key: (d: OracleWeightage) => d.id // oracleid
id = oracleid

2021-06-29 10:53 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +          console.log(e)
This is bad right?

2021-06-29 13:09 UTC, fuxingloh commented on src/module.indexer/model/oracle.weightage.ts
> +  async invalidate (block: RawBlock): Promise<void> {
atm there is no easy way to, I will refactor that in

2021-06-29 13:35 UTC, fuxingloh requested changes

2021-06-29 13:35 UTC, fuxingloh commented on src/module.model/oracle.weightage.ts
> +}
For Weightage, you also need to index it from a time-series data perspective. (This means you need to index the height). When you need to query the latest weightage, what you do is `getHighest()`. When a Weightage is removed you can mark it as the state: 'REMOVED' | 'LIVE'. This is because blockchain is immutable, and always time series. By doing so you can see a series of events that moves when the blockchain moves. Aka see the history of an oracle.

> For this scenario it's height as a time series variable. block height in an ever-increasing manner. similar to ScriptAggregationMapper with getLatest

Time series for reference:
1. https://en.wikipedia.org/wiki/Time_series
2. https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/time-series

2021-06-29 14:19 UTC, monstrobishi commented
Maybe not in this PR, but I'd like to see some E2E tests for these oracle indexers

2021-06-29 14:29 UTC, monstrobishi commented on src/module.model/oracle.weightage.ts
> +}
Just to be extra clear, use blockheight as index here not timestamp, then use in other PR: https://github.com/DeFiCh/whale/pull/177/files#r660674730

2021-06-29 14:42 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +        height: block.height
Added this

2021-06-29 14:42 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +      state
State can be LIVE or REMOVED

2021-06-29 14:44 UTC, jingyi2811 commented on src/module.model/oracle.weightage.ts
> +  async getLatest (id: string): Promise<OracleWeightage | undefined> {
Should I use hid? Like what was written in `script.aggregration.ts`

2021-06-29 14:45 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.ts
> +      //   aggregation.data.weightage = latest.data.weightage
I added the `getLatest `function. It is working correctly. I test it by uncommenting this block of code.

2021-06-29 14:46 UTC, jingyi2811 commented on src/module.indexer/indexer.spec/oracle.weightage.spec.ts
>      const weight = await weightageMapper.get(oracleid)
Missing `getLatest` interface in mapper class. If not I can add the test here

2021-06-29 14:50 UTC, jingyi2811 commented
I think eventually I need to expose `getLatest` function to the endpoint.

<img width="594" alt="Screenshot 2021-06-29 at 10 48 25 PM" src="https://user-images.githubusercontent.com/7101806/123819338-48512d00-d92c-11eb-89c4-6af66b976d1f.png">

2021-06-29 15:25 UTC, fuxingloh commented on src/module.model/oracle.weightage.ts
> +  async getLatest (id: string): Promise<OracleWeightage | undefined> {
you just need to provide a unique `id` this is for internal database tracking purposes, will be refactored out eventually

e.g. 
1. with just partition key = `id` as it's always unique
2. with both partition key and sort key, a unique `id` would be `partition key` + `sort key`

2021-06-30 07:34 UTC, monstrobishi commented on src/module.indexer/model/oracle.weightage.priceFeed.ts
> +
we can use else ifs here

2021-06-30 07:46 UTC, jingyi2811 commented on src/module.indexer/model/oracle.weightage.priceFeed.ts
> +
Sure!

2021-06-30 07:50 UTC, jingyi2811 commented
Added another mapper - Price Feed. (For eg: APPL / EUR, TESL / USD ...)

This is important because we want to know what is the distinct Price Feed available for every block. And, we use it to calculate the price

2021-06-30 07:57 UTC, jingyi2811 commented on src/module.indexer/model/oracle.priceFeed.ts
> +          const allPriceFeeds = await this.mapper.getAll() ?? []
Here, I try to do something like `select * from PriceFeed mapper where oracleId = blah blah blah`

This is what I wrote

I select all record
`
const allPriceFeeds = await this.mapper.getAll()`

Then, I select an individual record

`await this.mapper.getByOracleId(allPriceFeeds[y].id, oracleId)`

Seems silly. But it works. All the tests passed.

2021-06-30 08:05 UTC, jingyi2811 commented on src/module.indexer/indexer.spec/oracle.priceFeed.spec.ts
> +import { MasterNodeRegTestContainer } from '@defichain/testcontainers'
Need to improve every test by comparing the final result with RPC calls. I shall add this later.

2021-06-30 12:04 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/stub.service.ts
> +  async waitForIndexedHeight (height: number, timeout: number = 30000): Promise<void> {
Not sure I made a correct decision to add this

2021-06-30 12:05 UTC, jingyi2811 commented on src/module.api/oracle.status.controller.e2e.ts
> +    it('should return undefined if getAggregation with invalid id', async () => {
I think this should throw an exception

2021-07-01 13:10 UTC, fuxingloh requested changes

2021-07-01 13:10 UTC, fuxingloh commented on src/module.model/oracle.status.ts
> +  id: string // oracleid
`id` must be unique, `oracleid` is the partition key, `height` is the sort key
hence the unique would be oracle id + height

if it's not unique, you will be override itself.

make you you setup your tests so that it overrides itself.

use `oracleId` semantic for consistency on whale side.

> wasn't well documented by me

2021-07-02 06:03 UTC, fuxingloh commented on src/module.indexer/model/oracle.status.ts
> +        )
check [0] is the correct signature

2021-07-02 06:03 UTC, fuxingloh commented on src/module.indexer/model/oracle.status.ts
> +        }
you need to invalidate everything else too

2021-07-02 06:07 UTC, monstrobishi commented on packages/whale-api-client/src/api/oracle.ts
> +  async getAggregation (id: string): Promise<OracleStatusAggregration> {
This needs to be more self explanatory, infact nothing is being aggregated here, it's just Oracle status, so you can call this `getOracleStatus`

2021-07-02 06:08 UTC, monstrobishi commented on src/module.api/oracle.status.controller.ts
> +  @Get('/aggregation')
Call this oracle status

@fuxingloh what's the right convention for 2 word, is it kebab case

2021-07-02 06:09 UTC, monstrobishi commented on src/module.api/oracle.status.controller.ts
> +  @Get('/aggregation')
or oracle/status

2021-07-02 06:09 UTC, monstrobishi commented on src/module.api/oracle.status.controller.ts
> +  @Get('/aggregation')
ok I think just `status` works because it's behind the controller

2021-07-02 06:46 UTC, canonbrother requested changes

2021-07-02 06:46 UTC, canonbrother commented on src/module.model/oracle.status.ts
> +      limit: 100
1 data only

2021-07-02 06:46 UTC, canonbrother commented on src/module.model/oracle.status.ts
> +        key: (d: OracleStatus) => d.id // oracleId - height
```suggestion
        key: (d: OracleStatus) => d.id // oracleId + height
```

2021-07-02 07:50 UTC, jingyi2811 commented on src/module.indexer/model/oracle.status.ts
> +        )
Sorry, I don't understand.  Below is a complete stack object for OP_DEFI_TX_APPOINT_ORACLE.

```
  console.log
    [
      OP_RETURN { type: 'OP_RETURN', code: 106 },
      OP_DEFI_TX {
        type: 'OP_DEFI_TX',
        tx: {
          signature: 1147556984,
          type: 111,
          name: 'OP_DEFI_TX_APPOINT_ORACLE',
          data: [Object]
        }
      }
    ]
```

The value of [0] is  OP_RETURN { type: 'OP_RETURN', code: 106 }

Should I validate the value?

2021-07-02 07:55 UTC, jingyi2811 commented on src/module.model/oracle.status.ts
> +      limit: 100
I was testing something. Forget to switch back.

2021-07-02 09:09 UTC, jingyi2811 commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
If I appoint an Oracle and update it later, first mapper should has state = REMOVED right
If yes, what is the best way to doing that?

I actually think that `id = oracleId ` is better than `${oracleId}-${height1}`
Where I just need oracleId to update the original key

2021-07-02 09:10 UTC, monstrobishi commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
No it should not have REMOVED, only the block that it gets removed

2021-07-02 09:11 UTC, monstrobishi commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
We need the height so we know the weightage at that block height, when doing the price mapping

2021-07-02 09:12 UTC, monstrobishi commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
@fuxingloh how do we handle dependencies in mapping? is there a possibility the price mapper runs before the oracle status mapper, and then the status is not available for weightage calculation?

2021-07-02 09:37 UTC, jingyi2811 commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
<img width="206" alt="Screenshot 2021-07-02 at 5 34 30 PM" src="https://user-images.githubusercontent.com/7101806/124254632-d7905780-db5b-11eb-9697-4e5656e3b073.png"> 
 
I think they follow this order (See `_main.ts`)

2021-07-02 09:40 UTC, monstrobishi commented on src/module.indexer/indexer.spec/oracle.status.spec.ts
> +    expect(data1?.state).toStrictEqual(OracleState.LIVE)
ok great, then we just need to order it correctly

2021-07-04 14:04 UTC, fuxingloh requested changes

2021-07-04 14:04 UTC, fuxingloh commented on packages/whale-api-client/src/api/oracle.ts
> +export interface OracleStatus {
```suggestion
export interface OracleAppointed {
```

I think it's better to call it appointed since that's the action

2021-07-08 11:07 UTC, fuxingloh requested changes

2021-07-08 11:07 UTC, fuxingloh commented on src/module.api/oracle.appointed.controller.ts
> +
`@Get('/appointments')`

query appointments?

2021-07-08 11:07 UTC, fuxingloh commented on src/module.api/oracle.appointed.controller.ts
> +  }
I think we just need to query appointments `list` instead of get `one`

2021-07-08 11:07 UTC, fuxingloh commented on packages/whale-api-client/__tests__/stub.service.ts
> +  }
I think you should create a PR for this separately and get it merged in early. Since this is a non-breaking change.

2021-07-08 11:07 UTC, fuxingloh commented on src/module.api/oracle.appointed.controller.ts
> +export class OracleAppointedController {
to hold all oracles feature within this single controller

2021-07-08 11:38 UTC, fuxingloh commented on src/module.api/oracle.appointed.controller.ts
> +export class OracleAppointedController {
actually, now that I think about it, if there isn't a use case for exposing status/appointed data I think you should just remove it entirely.

2021-07-08 11:39 UTC, fuxingloh commented on src/module.api/oracle.appointed.controller.ts
> +export class OracleAppointedController {
since the weightage is just for internal calculation, nothing useful for external querying

2021-07-08 11:40 UTC, fuxingloh commented on src/module.model/oracle.appointed.ts
> +      name: 'oracle_status_oracleId_height',
btw to update all these `oracle_status` to `oracle_appointed`

2021-07-09 02:47 UTC, monstrobishi commented on src/module.model/oracle.appointed.ts
> +      name: 'oracle_status_oracleId_height',
I would rather rename the controller to `oracle.status.ts` and keep status, oracle.appointed doesn't make much sense here

2021-07-09 02:48 UTC, monstrobishi commented on src/module.model/oracle.appointed.ts
> +      name: 'oracle_status_oracleId_height',
Status is altered by appointed, updated and removed, so why name it based on only one of those triggers? And we are storing status here

2021-07-09 03:23 UTC, fuxingloh commented on src/module.model/oracle.appointed.ts
> +      name: 'oracle_status_oracleId_height',
My beliefs are:

1. `Oracle` works by `Appointment` through Foundation or Operator Space
2. With an `Appointment ` it allows an owner/actor to perform price feed update
3. Triggers such as `Updates` changes `Appointment` of an assigned owner/actor

Hence the status is the reflection of the oracle appointment rather than anything else.

2021-07-09 03:25 UTC, monstrobishi commented on src/module.model/oracle.appointed.ts
> +      name: 'oracle_status_oracleId_height',
Ok I guess that works as long as everything is consistent

2021-07-11 05:51 UTC, jingyi2811 commented on src/module.api/oracle.appointed.controller.ts
> +export class OracleAppointedController {
Ya, I also thought the same too.

2021-07-11 05:52 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/stub.service.ts
> +  }
Ok, sure!

2021-07-11 06:40 UTC, jingyi2811 commented
Close this PR. I shall apply all the comments and suggestions to https://github.com/DeFiCh/whale/pull/201

2021-07-11 06:41 UTC, closed without merging