Index price aggregration
DeFiCh/whale pull request #201
Opened 2021-07-01 14:38 UTC by jingyi2811

What kind of PR is this?:
/kind feature

What this PR does / why we need it:
Index price aggregration

Which issue(s) does this PR fixes?:
Fixes #144

Additional comments?:

2021-07-02 06:06 UTC, monstrobishi commented on src/module.model/oracle.priceData.ts
> +      gte: timestamp - 300,
Sorry disregard the earlier suggestion, let's keep this to 1 hour + 1 hour - same as C++ implementation

2021-07-06 03:06 UTC, jingyi2811 commented on src/module.model/oracle.priceData.ts
> +      gte: timestamp - 300,
Ok sure!

2021-07-07 06:38 UTC, monstrobishi commented
We should only need 2 indexers, not 4:
- Oracle Status, for status, price feed and weightage (this indexes AppointOracle, RemoveOracle and UpdateOracle TX)
- Price Data. for prices

2021-07-07 06:40 UTC, jingyi2811 commented
It is fine for me.

2021-07-07 06:44 UTC, monstrobishi requested changes

2021-07-07 06:44 UTC, monstrobishi commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPrice (token: string, currency: string): Promise<OraclePriceAggregration> {
we need a function that returns an array of prices across a time range with an interval.

E.g.

prices from 5th March to 10th March every 5 minutes (or blocks etc, if easier to implement)

2021-07-07 06:45 UTC, monstrobishi commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPrice (token: string, currency: string): Promise<OraclePriceAggregration> {
this is for drawing graphs

2021-07-07 06:59 UTC, jingyi2811 commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPrice (token: string, currency: string): Promise<OraclePriceAggregration> {
Ok sure.  Maybe something like
`getPrices(timestampFrom: number, timestampTo: number, interval: number) `

2021-07-07 07:00 UTC, jingyi2811 commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPrice (token: string, currency: string): Promise<OraclePriceAggregration> {
Also `async getPrice (token: string, currency: string)` is not enough
I need to add `async getPrice (token: string, currency: string, timestamp: number)` to query price at specific timestamp

2021-07-15 06:18 UTC, monstrobishi commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPriceChangePercentage (token: string, currency: string, timestamp1: number, timestamp2: number): Promise<BigNumber> {
is this needed for a specific page on the explorer?

2021-07-15 06:21 UTC, monstrobishi commented
This looks good, I'll approve once code coverage is improved

seems like the following have low coverage:

<html>
<body>
<!--StartFragment-->

.../module.indexer/model/oracle.price.aggregration.ts | 68.25% <68.25%> (ø) |  
-- | -- | --
src/module.indexer/model/oracle.appointed.ts | 71.02% <71.02%> (ø) |  
src/module.indexer/model/oracle.price.data.ts | 78.12% <78.12%> (ø)

<!--EndFragment-->
</body>
</html>

2021-07-15 06:26 UTC, jingyi2811 commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPriceChangePercentage (token: string, currency: string, timestamp1: number, timestamp2: number): Promise<BigNumber> {
Jonathan removed the 24 hour price change percentage from his latest prototype
https://marvelapp.com/prototype/74de579/screen/80840940

I will confirm with him again

2021-07-15 06:27 UTC, jingyi2811 commented on packages/whale-api-client/src/api/oracle.ts
> +  async getPriceChangePercentage (token: string, currency: string, timestamp1: number, timestamp2: number): Promise<BigNumber> {
Ok, this is what he told me
=> gathered feedback on it about it not being important for the user's using oracles

Okay, I shall remove the endpoint.

2021-07-15 06:34 UTC, jingyi2811 commented
> This looks good, I'll approve once code coverage is improved
> 
> seems like the following have low coverage:
> 
> .../module.indexer/model/oracle.price.aggregration.ts	68.25% <68.25%> (ø)	 
> src/module.indexer/model/oracle.appointed.ts	71.02% <71.02%> (ø)	 
> src/module.indexer/model/oracle.price.data.ts	78.12% <78.12%> (ø)

All these files has an invalidate function, which is still unable to be tested.

Fuxing will refactor the whale code again. See his comment: https://github.com/DeFiCh/whale/pull/191#discussion_r660500874

2021-07-16 08:22 UTC, fuxingloh requested changes

2021-07-19 02:39 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +
Should be checking vout type is `setOracleData` here? Otherwise the price will be no changes right? @monstrobishi please help to confirm.

2021-07-19 02:47 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +            sum += priceData.data.amount * weightage
BigNumber for precision.

2021-07-19 02:48 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +
Actually the rest of the function makes no use of the `txn` or the `vout`, @fuxingloh can you help to take a look as I might be missing something but the forloop here seems unecessary? maybe even a separate indexer

2021-07-19 02:50 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +
I think this code could live inside `appointedWeightageMapper`, or we can keep it as a separate indexer without the for loop above, but better to reduce the amount of indexers if we're not actually making use of the data in the block aside from block time and block height

2021-07-19 02:50 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +
(By separate indexer I mean this indexer that I'm commenting on, not an entirely new one)

2021-07-19 03:00 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
`this.priceDataMapper.getActivePrices` seems to query all the data in plus minus 1 hour (not sure 3600 is second or milli). This will potentially delete/invalidate `aggregation` belongs to older block?

2021-07-19 03:02 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
yes good spotting @ivan-zynesis !

2021-07-19 03:03 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +    for (const txn of block.tx) {
As (token, currency, block height/time) combination will be unique (based on my understanding on [L58](https://github.com/DeFiCh/whale/pull/201/files#diff-4b10347138343828d8ad3aeb7eb9b6b48313639f6166da974ba745a36408de7fR58)), no loop will be needed here, can invalidate everything (token currency pair) once for this block height.

2021-07-19 03:03 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
I see some potential issues but this only deletes the aggregated price at that block time, however block height <-> block time is not a strict mapping (some blocks can come before or after), so I see some potential issues here

2021-07-19 03:05 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
we may need to have another id in the key (e.g. block height) that is consistent for a specific block, so that we can support invalidation

2021-07-19 03:06 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +    for (const txn of block.tx) {
based on your comments I think we really need the unit tests for invalidation before this is live, as there are a lot of edgecases

2021-07-19 03:16 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.data.ts
> +                    priceDataObj.state = OracleState.REMOVED
Everything in oraclePriceData are occurred history, I wonder is this necessary.

2021-07-19 04:55 UTC, jingyi2811 commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
@monstrobishi Height is one of the keys for all mapper object

2021-07-19 06:07 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.aggregration.ts
> +          const priceDataResult = await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? []
ok then we should use height to invalidate here not time, it's more deterministic

2021-07-21 08:27 UTC, monstrobishi commented on src/module.indexer/model/oracle.appointed.ts
> +            }
I feel we don't want to set REMOVED on the old data, as REMOVED represents the Oracle state being removed, it does not represent the Oracle was updated

2021-07-21 08:38 UTC, monstrobishi commented on src/module.indexer/model/oracle.appointed.ts
> +            }
Don't need to set REMOVED here

2021-07-21 08:38 UTC, monstrobishi commented on src/module.indexer/model/oracle.appointed.ts
> +                priceDataRecords[`${oracleId}-${token}-${currency}-${height}-${timestamp.toString()}`] = priceDataObj
Don't need to set REMOVED here

2021-07-21 08:40 UTC, monstrobishi commented on src/module.indexer/model/oracle.appointed.ts
> +              weightageRecords[`${oracleId}-${height}`] = weightageObj
set weightage to 0 here

2021-07-21 12:16 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +      }
We are not invalidating `OP_DEFI_TX_REMOVE_ORACLE` here, need to handle that also

2021-07-21 12:21 UTC, monstrobishi commented on src/module.api/oracle.controller.ts
> +      @Param('timestamp2') timestamp2: number,
`timestamp1` -> `start`
`timestamp2` -> `end`

2021-07-21 12:25 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +    private readonly appointedTokenCurrencyMapper: OracleAppointedTokenCurrencyMapper,
I think we can combine `OracleAppointedWeightageMapper` and `OracleAppointedTokenCurrencyMapper`

2021-07-21 12:30 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +          } else if (stack[1]?.tx?.name === 'OP_DEFI_TX_UPDATE_ORACLE') {
`OP_DEFI_TX_APPOINT_ORACLE` and `OP_DEFI_TX_UPDATE_ORACLE` have very similar logic, see if you can combine it into another function or similar

2021-07-21 12:33 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +            for (let i = 0; i < tokens.length; i += 1) {
```suggestion
            tokens.forEach(token => {
```

2021-07-21 12:33 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +              for (let j = 0; j < prices.length; j += 1) {
```suggestion
            prices.forEach(price => {
```

2021-07-21 12:34 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +                priceDataRecords[`${oracleId}-${token}-${currency}-${block.height}-${timestamp.toString()}`] = OracleAppointedIndexer.newOraclePriceData(block.height, oracleId, token, currency, new B
```suggestion
priceDataRecords[`${oracleId}-${token}-${currency}-${block.height}-${timestamp.toString()}`] = 
  OracleAppointedIndexer.newOraclePriceData(
    block.height,
    oracleId,
    token,
    price.currency,
    new BigNumber(price.amount),
    timestamp,
    OracleState.LIVE)
```

2021-07-21 12:36 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +                priceDataRecords[`${oracleId}-${token}-${currency}-${block.height}-${timestamp.toString()}`] = OracleAppointedIndexer.newOraclePriceData(block.height, oracleId, token, currency, new B
Try to structure the other lines like this, much easier to read. For the const vars above can just insert them directly like this

2021-07-21 12:38 UTC, monstrobishi commented on src/module.indexer/model/oracle.price.ts
> +      await this.appointedWeightageMapper.put(record)
If we only need to store the values then we don't need the key in the objects above, they can just be arrays

2021-07-22 18:02 UTC, monstrobishi commented on packages/whale-api-client/__tests__/api/oracle.test.ts
> +let container: MasterNodeRegTestContainer
I suspect all of the describe sections should have their own container reference, otherwise you could face a race condition

2021-07-22 18:03 UTC, monstrobishi commented on src/module.indexer/indexer.spec/oracle.price.aggregration.spec.ts
> +    await container.start()
We probably need individual container references here, since we are calling start multiple times on the same reference

2021-07-27 10:39 UTC, ivan-zynesis requested changes

2021-07-27 10:39 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +        const priceDataObj = await this.priceDataMapper.getLatestByOracleIdTokenCurrency(oracleId, token, currency, block.height)
If I understand it correct ([indexer](https://github.com/DeFiCh/whale/pull/201/files#diff-a91ee61cc611bf57533a003129a5324bed0833e7fe205cfe5b20d20d02152889R77)), each `<oracle-id>-<token>-<currency>` can have more than 1 price tick in one block right? `getLatest...()` has limit 1 omits any older ticks.

2021-07-27 10:39 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +      id: `${token}-${currency}-${height}-${blockTime}`,
`blockTime` doesnt seems necessary as part of id, since aggregated once per block.

2021-07-27 10:39 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +      await this.priceDataMapper.delete(id)
```suggestion
      await this.priceAggregrationMapper.delete(id)
```

2021-07-27 10:39 UTC, ivan-zynesis commented on src/module.indexer/model/oracle.price.aggregration.ts
> +      const priceDataResult = (await this.priceDataMapper.getActivePrices(token, currency, block.time) ?? [])
`indexer.invalidate()` is also running in forward manner. The priceData of this block most likely already deleted by now.
But make sense to make the main `this.indexer.reverse().forEach(idx => idx.invalidate()` instead

cc: @fuxingloh

2021-07-27 14:11 UTC, canonbrother commented on src/module.api/oracle.controller.ts
> +      @Param('timestamp') timestamp: number
if not mistaken, you need parseInt on ts

2021-07-27 14:16 UTC, canonbrother commented on src/module.api/oracle.controller.ts
> +      @Param('timeInterval') timeInterval: number,
parseInt

2021-07-27 14:22 UTC, canonbrother commented on src/module.api/oracle.controller.ts
> +      if (index >= 0) {
have this got `-ve` index??

2021-07-27 14:25 UTC, canonbrother commented on src/module.model/oracle.appointed.token.currency.ts
> +      name: 'oracle_appointed_token_currency_oracleId-tokenCurrencyHeight',
```suggestion
      name: 'oracle_appointed_token_currency_oracleId_tokenCurrencyHeight',
```

2021-07-27 14:44 UTC, canonbrother commented on src/module.model/oracle.appointed.weightage.ts
> +      name: 'oracle_appointed_weightage_oracleId-height',
```suggestion
      name: 'oracle_appointed_weightage_oracleId_height',
```

2021-07-27 14:50 UTC, canonbrother commented on src/module.model/oracle.price.aggregration.ts
> +      name: 'oracle_price_aggregration_tokenCurrency-heightBlockTime',
```suggestion
      name: 'oracle_price_aggregration_tokenCurrency_heightBlockTime',
```

2021-07-27 14:52 UTC, canonbrother commented on src/module.model/oracle.price.aggregration.ts
> +      lte: blockTime,
hmm... weird.. is this working??

2021-07-27 14:54 UTC, canonbrother commented on src/module.model/oracle.price.data.ts
> +      name: 'oracle_price_data_oracleId-tokenCurrencyAmountHeight',
```suggestion
      name: 'oracle_price_data_oracleId_tokenCurrencyAmountHeight',
```

2021-07-27 14:55 UTC, canonbrother commented on src/module.model/oracle.price.data.ts
> +      name: 'oracle_price_data_oracleIdTokenCurrency-height',
```suggestion
      name: 'oracle_price_data_oracleIdTokenCurrency_height',
```

2021-07-27 14:55 UTC, canonbrother commented on src/module.model/oracle.price.data.ts
> +      name: 'oracle_price_data_tokenCurrency-timestamp',
```suggestion
      name: 'oracle_price_data_tokenCurrency_timestamp',
```

2021-07-27 15:00 UTC, canonbrother commented on src/module.model/oracle.price.data.ts
> +        key: (d: OraclePriceData) => `${d.data.token}-${d.data.currency}-${d.data.amount.toString()}-${d.block.height}`
the `interface OraclePriceData` should belong to here
those model interface should belong to model layer

2021-07-27 15:03 UTC, canonbrother commented on src/module.model/oracle.price.data.ts
> +        key: (d: OraclePriceData) => `${d.data.token}-${d.data.currency}-${d.data.amount.toString()}-${d.block.height}`
is this how the `OraclePriceData.id` looks like??
can you move your model interface here? and note the id construction pattern?

2021-07-27 15:15 UTC, canonbrother requested changes
too many duplicated fixture set up, can you refactor it?
will do another round review after cleanup...

2021-07-28 03:32 UTC, canonbrother commented on src/module.api/oracle.controller.ts
> +  @Get('/token/currency')
@fuxingloh do we follow plural convention in api??

2021-07-28 04:00 UTC, fuxingloh commented on src/module.api/oracle.controller.ts
> +  @Get('/token/currency')
hmm, yeah, we have it. I will refactor this PR

2021-07-28 04:10 UTC, monstrobishi commented on src/module.api/oracle.controller.ts
> +      @Param('timestamp') timestamp: number
I think take as string and parse to bignumber? Although unlikely for timestamp to need that precision, but on blockchain side it's 64 bit int

2021-07-28 04:10 UTC, monstrobishi commented on src/module.api/oracle.controller.ts
> +      @Param('timestamp') timestamp: number
Also do we want to standardise on milliseconds timestamp, because blockchain side uses seconds, I think controller should do milliseconds though

2021-07-28 04:22 UTC, canonbrother commented on src/module.api/oracle.controller.ts
> +      @Param('timestamp') timestamp: number
yea actually we don't really need to concern the timestamp precision as it has no decimal
but the `timestamp` came from API URL which is `string` but the usecase is `number`

```async getLatestByTokenCurrencyBlockTime (token: string, currency: string, blockTime: number):```

so far my review breakpoint here i'd ask for using `parseInt` which is part of nestjs controller feature

regarding the timestamp digit.. should standardise on milliseconds due to native js ts
but also need to check the length of timestamp, just in case, `if (ts.length === 10) ts * 1000`

2021-07-30 12:18 UTC, fuxingloh commented
Closed in favor of https://github.com/DeFiCh/whale/pull/281

> Significant refactor to move logic into indexer instead of Controller as the controller should not have any logic. Aggregation is thus also moved to price feed as each block height if there are any price feed.

2021-07-30 12:18 UTC, closed without merging