added poolpair `priceRatio` and `totalLiquidityUsd`
DeFiCh/whale pull request #202
Opened 2021-07-01 15:06 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes part of #136

2021-07-08 11:03 UTC, fuxingloh requested changes

2021-07-08 11:03 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +    return await this.rpcClient.poolpair.testPoolSwap(metadata)
I was wondering why you need this,

you don't need this to calculate the trading pair, you can just

> `'reserveA/reserveB': BigNumber | string`

find the pair DFI-USDT
where `a=DFI,b = USDT` via get poolpair

giving you the ratio

Because `testpoolpair` has reliance on consensus logic, where the above lookup doesn't allow for more agnostic replacement. (e.g. when we move to use whale index instead of reading from ain.)

2021-07-09 02:43 UTC, monstrobishi commented
Unblocks https://github.com/DeFiCh/salmon/issues/77

2021-07-09 03:59 UTC, canonbrother commented on src/module.api/poolpair.service.ts
> +    return await this.rpcClient.poolpair.testPoolSwap(metadata)
oh.. i just realized.. updated!!

2021-07-16 06:35 UTC, fuxingloh requested changes
2 Minor Changes, afterward I wanna do a minor refactoring PR into this branch to make it more resistant to code evolution

2021-07-16 06:35 UTC, fuxingloh commented on packages/whale-api-client/src/api/poolpair.ts
> +    'tokenB/tokenA': string // BigNumber | string
```suggestion
    ab: string // BigNumber | string
    ba: string // BigNumber | string
```

so that we can access it naturally without using `[]` for data access consistency across platform

2021-07-16 06:35 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +let poolPairService: PoolPairService
for `.test.ts` and `e2e.ts` instead of mock spying how about creating a `DFI-USDT` pair? It only make sense to spy/mock on unitized testing

Since they are supposed to be e2e.

2021-07-21 03:16 UTC, fuxingloh commented
Reviewing this now, I might make changes to this PR directly

2021-07-23 06:22 UTC, monstrobishi approved these changes

2021-07-23 06:49 UTC, fuxingloh approved these changes

2021-07-23 06:49 UTC, merged