Masternode controller
DeFiCh/whale pull request #204
Opened 2021-07-04 23:31 UTC by siradji

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-07-07 05:07 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const paginationSize = (initialLength / 2)
Remove unnecessary open bracket and close bracket

2021-07-07 05:11 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const first = await client.masternodes.list(paginationSize)
Need to add `expect(first.hasNext).toStrictEqual(true)`

2021-07-07 05:11 UTC, jingyi2811 commented on packages/whale-api-client/src/whale.api.client.ts
>    constructor (
You need to add back break line

2021-07-07 05:11 UTC, jingyi2811 commented on src/module.api/_module.ts
> +import { MasternodesController } from '@src/module.api/masternode.controller'
You need to add back break line

2021-07-07 11:15 UTC, jingyi2811 commented on src/module.api/masternode.controller.ts
> +  ): Promise<any> {
The return type shouldn't be any

2021-07-07 11:28 UTC, jingyi2811 commented on packages/whale-api-client/src/api/masternode.ts
> +   * @return {Promise<ApiPagedResponse<TokenData>>}
Isn't this should be MasternodeData?

2021-07-08 07:19 UTC, fuxingloh requested changes
You need to remap to use a more natural nested hierarchy

for context https://github.com/DeFiCh/whale/pull/83#discussion_r634973447

2021-07-08 07:19 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +  localMasternode: boolean
```suggestion
```

remove these, don't map these. It's not applicable within whale/ocean infrastructure setup as it will not own any masternode on defid.

2021-07-08 07:19 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +  banTx: string
```suggestion
```

remove these, they are deprecated or will be soon

2021-07-08 07:19 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +  resignTx: string
```suggestion
  resign: {
    height: number
    tx: string
  }
```

structure it like this

2021-07-08 07:19 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +  creationHeight: number
creation.height

2021-07-08 07:19 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +  operatorAuthAddress: string
- `owner.address`
- `operator.address`

2021-07-08 07:19 UTC, fuxingloh commented on src/module.api/masternode.controller.ts
> +function mapMasternodeData (id: string, MasternodeInfo: MasternodeInfo): MasternodeData {
```suggestion
function mapMasternodeData (id: string, info: MasternodeInfo): MasternodeData {
```

follow naming convention

2021-07-08 07:19 UTC, fuxingloh commented on src/module.api/masternode.controller.ts
> +
```suggestion
```

2021-07-08 07:19 UTC, fuxingloh commented on src/module.api/masternode.controller.ts
> +    if (query.next !== undefined) options.start = query.next
I think you can write it similar to this, IMO it's easier to follow 

https://github.com/DeFiCh/whale/blob/1d3a4268be91c16d13a9955879e0ac43836fad8a/src/module.api/token.controller.ts#L24-L26

2021-07-08 10:14 UTC, siradji commented on src/module.api/masternode.controller.ts
> +    if (query.next !== undefined) options.start = query.next
As the start option for a masternode is a string (id for masternode) we can not implement it the same way.  I tried that way first and it was failing.

2021-07-08 10:44 UTC, fuxingloh commented on src/module.api/masternode.controller.ts
> +    if (query.next !== undefined) options.start = query.next
something like this:

```ts
start: query.next, 
including_start: query.next === undefined, 
limit: query.size 
```

2021-07-08 11:01 UTC, siradji commented on src/module.api/masternode.controller.ts
> +    if (query.next !== undefined) options.start = query.next
You are right. Implemented and pushed together with all the changes requested.

2021-07-08 11:50 UTC, jingyi2811 approved these changes

2021-07-08 11:58 UTC, jingyi2811 commented on src/module.api/masternode.controller.ts
> +    id: id,
Change to `id` only

2021-07-08 12:32 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +   * @param {number} next next set of masternodes
```suggestion
   * @param {string} next set of masternodes to query
```

2021-07-08 12:44 UTC, fuxingloh requested changes

2021-07-08 12:44 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
use fixed numbers for this, all test must be deterministic 

you need to create a few masternode to setup your scenarios.

2021-07-08 12:44 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
similar to this 
https://github.com/DeFiCh/whale/blob/e0422e76a9796a068f7ebcc2ba8d3c0358c1ff4d/packages/whale-api-client/__tests__/api/poolpair.test.ts#L28-L35

2021-07-08 16:02 UTC, siradji commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
oh.. i guess for this i need to add `createMasternode` to `@defichain/testing` utils

2021-07-08 17:56 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
it's not mandatory you can just use the json rpc client directly where you have it mapped

https://github.com/DeFiCh/whale/blob/95dc6115cc7d146ff554536d2c875ae3c7082b7c/src/module.api/poolpair.controller.spec.ts#L16

2021-07-08 17:58 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
Actually, the existing masternode that is part of genesis, you just use that instead. I think there are `8` which should be enough to test pagination.

2021-07-08 18:04 UTC, siradji commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
Yes i know of the existing masternode but I thought it will change based on the testing env (CI or locally) and that is why i did not use a fix number. Let me do that.

2021-07-08 18:04 UTC, siradji commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
> Actually, the existing masternode that is part of genesis, you just use that instead. I think there are `8` which should be enough to test pagination.

Yes i know of the existing 8 existing but I thought it will change based on the testing env (CI or locally) and that is why i did not use a fix number. Let me do that.

2021-07-08 18:14 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    const lastIndex = paginationSize - 1
the testing env is determinstic, I think you can safely assume `8` at genesis

2021-07-09 10:07 UTC, jingyi2811 approved these changes

2021-07-11 21:58 UTC, siradji commented
@fuxingloh , all changes are done.

2021-07-14 09:17 UTC, canonbrother commented on packages/whale-api-client/src/api/masternode.ts
> +    return await this.client.requestData('GET', `masternodes/${id}`)
```suggestion
    const masternode = await this.client.requestData('GET', `masternodes/${id}`)
    if (masternode === undefined) {
      throw new NotFoundException(`Unable to find masternode by id: ${id}`)
     }
```

2021-07-14 09:23 UTC, canonbrother requested changes
normally we need handle `get` if undefined but list (it will just a empty array)

overall code is clean and consistent

2021-07-14 09:24 UTC, canonbrother commented on src/module.api/masternode.controller.spec.ts
> +describe('get', () => {
here missing the non-existence masternode test

2021-07-15 00:56 UTC, siradji commented on packages/whale-api-client/src/api/masternode.ts
> +    return await this.client.requestData('GET', `masternodes/${id}`)
@canonbrother, is this necessary as the not found has already been taken care of in the `masternode.controller`

```javascript
async get (@Param('id') id: string): Promise<MasternodeData> {
    try {
      const data = await this.client.masternode.getMasternode(id)
      return mapMasternodeData(id, data[Object.keys(data)[0]])
    } catch (err) {
      if (err?.payload?.message === 'Masternode not found') {
        throw new NotFoundException('Unable to find masternode')
      } else {
        throw new BadRequestException(err)
      }
    }
  }
```

2021-07-15 00:58 UTC, siradji commented on src/module.api/masternode.controller.spec.ts
> +describe('get', () => {
I also believe this has already been implemented. Let me change the test name for better understanding. 

```javascript
  it('should fail and throw an error with wrong id', async () => {
    const id = '8d4d987dee688e400a0cdc899386f243250d3656d802231755ab4d28178c9816'
    try {
      await controller.get(id)
    } catch (err) {
      expect(err).toBeInstanceOf(NotFoundException)
      expect(err.response).toStrictEqual({
        statusCode: 404,
        message: 'Unable to find masternode',
        error: 'Not Found'
      })
    }
  })
```

2021-07-15 02:24 UTC, ivan-zynesis commented on packages/whale-api-client/src/api/masternode.ts
> +    return await this.client.requestData('GET', `masternodes/${id}`)
Not necessary, the 404 NotFound error shown in test is good enough.

2021-07-15 02:48 UTC, canonbrother commented on packages/whale-api-client/src/api/masternode.ts
> +    return await this.client.requestData('GET', `masternodes/${id}`)
ohh.. my bad... it's client.. it just receive whatever from core return will do

2021-07-15 02:51 UTC, canonbrother approved these changes

2021-07-15 04:05 UTC, jingyi2811 submitted a review, later dismissed

2021-07-16 03:14 UTC, fuxingloh commented on src/module.api/masternode.controller.spec.ts
> +    } catch (err) {
```suggestion
    expect.assertions(2)
    try {
      await controller.get('8d4d987dee688e400a0cdc899386f243250d3656d802231755ab4d28178c9816')
    } catch (err) {
```

2021-07-16 03:15 UTC, fuxingloh commented on src/module.api/masternode.controller.e2e.ts
> +    } catch (err) {
```suggestion
    expect.assertions(2)
    try {
      await controller.get('8d4d987dee688e400a0cdc899386f243250d3656d802231755ab4d28178c9816')
    } catch (err) {
```

2021-07-16 03:18 UTC, fuxingloh requested changes

2021-07-16 03:18 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternode.test.ts
> +    expect(data.nextToken).toStrictEqual(undefined)
You need to assert data structure at least once in `list` and `get` to prevent regression

e.g.
https://github.com/DeFiCh/whale/blob/13922b3f66b829e9fa196c40479f38bb40a6b0ac/packages/whale-api-client/__tests__/api/poolpair.test.ts#L77-L101

2021-07-16 07:10 UTC, fuxingloh requested changes

2021-07-16 07:10 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternode.ts
> +   * Query information about a masternode with given id.
```suggestion
   * Get information about a masternode with given id.
```

2021-07-16 11:41 UTC, jingyi2811 approved these changes

2021-07-16 12:36 UTC, fuxingloh approved these changes

2021-07-16 12:36 UTC, merged