Index customTx `createtoken`, `createpoolpair` and `updatepoolpair`
DeFiCh/whale pull request #215
Opened 2021-07-06 07:55 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Index createtoken, createpoolpair, and updatepoolpair.
Reducing number of rpcClient calls and indexes are faster.
Block #185 

#### Which issue(s) does this PR fixes?:

Fixes part of #136

2021-07-07 10:38 UTC, ivan-zynesis commented on src/module.indexer/model/token.ts
> +            const id = (Number(token.id) + 1).toString() // id increment
Can't tell if there is any better (easy) way to retrieve this.
Currently implementation there is risk where normal token and LM token id jumble up

Indexer run single threaded, from one model to another model. I guess the token id assigned by defid should be increment chronologically, which can be creating new LM token then another normal token within the same block.

Might be no occurrence so far in the chain now. More than one token creation within one block can happen quite frequently when more product (stock, commodity etc) released, chances is there.

2021-07-07 11:01 UTC, ivan-zynesis commented on src/module.model/poolpair.ts
> +        key: (p: PoolPair) => p.poolId
If I understand how this ModelMapping work, `poolId` is also the unique token id right, then it will become one partition per poolpair and each partition has one row.

2021-07-07 12:36 UTC, canonbrother commented on src/module.indexer/model/token.ts
> +            const id = (Number(token.id) + 1).toString() // id increment
yea i made a mistake here.. hmm... i should create another index the especially for `tokenId`

2021-07-07 12:38 UTC, canonbrother commented on src/module.model/token.ts
> +        key: (t: Token) => t.block.height
yes for now.. its more on `sort` here

2021-07-07 12:44 UTC, canonbrother commented on src/module.model/poolpair.ts
> +        key: (p: PoolPair) => p.poolId
yea `poolId` is also the unique token, but rather i set `tokenA-tokenB` as primary key here

the reason is to adopt poolswap block logic
what will retrieve from poolswap block is `fromTokenId` and `toTokenId`
usage:
```
poolpairMapper.get(`${fromTokenId}-${toTokenId}`
```

2021-07-07 12:45 UTC, canonbrother commented on src/module.model/poolpair.ts
> +        key: (p: PoolPair) => p.poolId
its actually quite much tricky and workaround to structure the token and poolpair in LSM :sweat_smile:

2021-07-07 14:47 UTC, canonbrother commented on src/module.indexer/model/token.ts
> +            const id = (Number(token.id) + 1).toString() // id increment
added `dctId` index

2021-07-08 06:18 UTC, fuxingloh requested changes

2021-07-08 07:07 UTC, fuxingloh commented
I think instead of tracking DCT_ID increment via poolpair and token creation, we can just track `createpoolpair` and `updatepoolpair` DfTX and use the existing RPC protocol to find the actual `poolId`, this will cut down the number of indexes we have for now. 

Since RawBlock that you receive are already indexed in c++, the id should already be available. And you can use txid to get poolpair id.

The reason is for us to move so quickly to a full parity with c++ will be jarring as we will need to manage more state at whale. Increasing the complexity fold rather quickly, prefer to slowly increase to catch implementation issues.

2021-07-12 09:01 UTC, jingyi2811 commented on src/module.indexer/model/poolpair.ts
> +        if (vout.scriptPubKey.asm.startsWith('OP_RETURN 4466547870')) { // 44665478 -> DFTX, 70 -> p -> create poolpair
Initially I used number like `4466547870` But Fuxing asked me to change
See https://cakedefi.slack.com/archives/C01VBBJ8561/p1624344682274200?thread_ts=1624335293.268200&cid=C01VBBJ8561

Below is my latest code

```
    for (const txn of block.tx) {
      for (const vout of txn.vout) {
        if (!vout.scriptPubKey.hex.startsWith('6a')) {
          continue
        }

        const stack: any = toOPCodes(
          SmartBuffer.fromBuffer(Buffer.from(vout.scriptPubKey.hex, 'hex'))
        )

        if (stack[0]?.type === 'OP_RETURN' || stack[0]?.code === '106') {
          if (stack[1]?.tx?.name === 'OP_DEFI_TX_APPOINT_ORACLE') {
```

2021-07-12 12:45 UTC, canonbrother commented on src/module.indexer/model/poolpair.ts
> +        if (vout.scriptPubKey.asm.startsWith('OP_RETURN 4466547870')) { // 44665478 -> DFTX, 70 -> p -> create poolpair
@jingyi2811  
its different as your previous implementation hardcoded the length
```
async index (block: RawBlock): Promise<void> {
  const records: Record<string, OraclePrice> = {}
  for (const txn of block.tx) {
    if (txn.hex.includes('6a414466547879')) {
      const buffer = SmartBuffer.fromBuffer(Buffer.from(txn.hex, 'hex'))
      const composable: any = new CSetOracleData(buffer)
```

2021-07-12 13:25 UTC, jingyi2811 commented on src/module.indexer/model/poolpair.ts
> +        if (vout.scriptPubKey.asm.startsWith('OP_RETURN 4466547870')) { // 44665478 -> DFTX, 70 -> p -> create poolpair
Ah, okay.

2021-07-13 02:50 UTC, ivan-zynesis commented on src/module.indexer/model/token.ts
> +          if (Object.keys(tokens).length === 0) {
I think can reduce some codes here, effectively they behave the same.
```suggestion
          const token = tokens[data.symbol]
          if (token === undefined) throw new RpcNotFoundIndexerError('listTokens', data.symbol)
```

2021-07-13 02:59 UTC, ivan-zynesis commented on src/module.indexer/model/poolpair.ts
> +          const rpcPoolPair = await this.client.poolpair.getPoolPair(pairSymbol)
```suggestion
          const rpcPoolPair = await this.client.poolpair.getPoolPair(pairSymbol)
          if (Object.keys(rpcPoolPair).length !== 1) throw
```
Can put a guard here, the indexer will make noise if same pair allowed in defid from different operator in future.

2021-07-13 03:07 UTC, ivan-zynesis requested changes

2021-07-13 03:07 UTC, ivan-zynesis commented on src/module.indexer/model/poolpair.ts
> +          await this.mapper.delete(poolpair.id)
Should be a major flow, cant be invalidating `PoolUpdatePair` deleting the poolPair entirely.
hmm, this requires some data structure (huge) changes to fix.

2021-07-13 03:14 UTC, canonbrother commented on src/module.indexer/model/token.ts
> +          if (Object.keys(tokens).length === 0) {
yea that's an ideal way but that has design issue, the resp is out of expected
```
{ '0': ...token, '1', ...token }
```

2021-07-13 07:16 UTC, canonbrother commented on src/module.indexer/model/token.ts
> +            const id = (Number(token.id) + 1).toString() // id increment
solution was replaced by `rpc call`
https://github.com/DeFiCh/whale/pull/215#issuecomment-876188687

2021-07-16 07:05 UTC, fuxingloh commented on src/module.model/token.ts
> +import { Database, SortOrder } from '@src/module.database/database'
do we need tokens to be indexed? since you just need `module.model.poolpair.ts`

2021-07-16 07:05 UTC, fuxingloh commented on src/module.model/poolpair.ts
> +    }
Little confused about this index purpose, shouldn't it be

```suggestion
    poolId: {
      name: 'poolpair_poolId_height',
      partition: {
        type: 'string',
        key: (p: PoolPair) => p.poolId
      },
      sort: {
        type: 'height',
        key: (p: PoolPair) => p.block.height
      }
    }
```

for you to `getLatest(poolId)` information about the poolpair

2021-07-19 05:58 UTC, canonbrother commented on src/module.model/poolpair.ts
> +    }
because the usecase i was trying to make the query do this way
```ts
const poolpairs = await mapper.query() // list

const poolpair = await mapper.get('3') // get

const latest = await mapper.getLatest() // return latest poolpair
```
its a very simple design like block
so if set `sort` which the query will become
```ts
const poolpairs = await mapper.query('3') // return ??
```

2021-07-19 06:01 UTC, canonbrother commented on src/module.model/token.ts
> +import { Database, SortOrder } from '@src/module.database/database'
hmm.. because technically the poolpair is part of token
and i also think we will have token list design also
https://dex.defichain.com/mainnet/token

2021-07-19 08:19 UTC, fuxingloh commented on src/module.model/token.ts
> +import { Database, SortOrder } from '@src/module.database/database'
I think because for now I rather we piggy back on ain for tokens API and only implement what we need.

2021-07-19 08:27 UTC, fuxingloh commented on src/module.model/poolpair.ts
> +    }
For the PoolPair indexes by right you should not be tracking `PoolPair` you should be tracking `PoolPairMutations` changes.

This means you track changes within PoolPair as it processes within the blockchain. `getLatest('poolId')` allow you to get the latest mutated change of that PoolPair to use for calculation of something else.

2021-07-21 05:42 UTC, canonbrother commented on src/module.model/poolpair.ts
> +    }
hmm.. @fuxingloh
In order to adopt poolswap index, the sources only container `fromTokenId` and `toTokenId`
so the poolpair index id will be constructed by tokenA-tokenB
while tracking `mutations`, then will have to store diff poolpair id, perhaps construct the id by tokenA-tokenB-{something}
then issue comes back to poolswap index, you got idea to get poolpair by id?? 

https://github.com/DeFiCh/whale/blob/539e9bed73c0736d908335a2f95146fd3f54c9d9/src/module.indexer/model/poolswap.aggregation.ts#L29-L42

2021-07-21 08:41 UTC, fuxingloh commented on src/module.model/poolpair.ts
> +    }
That would be `a-b-height` since height is mutating upwards.

You don't need to know something, you just need to get `a-b-` hence using getLatest() or getHighest()

For example `script.aggregation`, it uses the latest to get previous and build on top of it. This works because the ledger is always moving forward and getLatest is always the most recent.

https://github.com/DeFiCh/whale/blob/16d0f9813705dab2d9297f8301ee610c46dc3567/src/module.indexer/model/script.aggregation.ts#L58-L72

2021-07-21 09:18 UTC, canonbrother commented on src/module.model/poolpair.ts
> +    }
hmm. i put poolId as partition key currently, if that case then
```ts
// from
model {
  id: tokenAId-tokenBId // unique
  poolId: '2', // partition
  height: 22, // sort
}

// to
model {
  id: tokenAId-tokenBId-height
  symbolId:  tokenAId-tokenBId // partition
  height // sort
  poolId
}
```

2021-07-22 09:12 UTC, fuxingloh commented on src/module.model/poolpair.ts
> +    }
yup, this works, you can choose to use `poolId` or `tokenAId-tokenBId` 

depending on your use case, I think yours is `require getLatest(tokenAId-tokenBId)`?

2021-07-22 09:15 UTC, canonbrother commented on src/module.model/poolpair.ts
> +    }
yes use tokenAId-tokenBId is more straight forward due to poolswap object design, the current implementation is kind of tweaking around the workflow to set poolId as partitionKey :sweat_smile:

2021-07-28 04:49 UTC, monstrobishi requested changes
Are you able to add invalidation tests for code coverage?

See
https://github.com/DeFiCh/whale/blob/main/src/module.indexer/indexer.spec/block.spec.ts#L60

and

https://github.com/DeFiCh/whale/blob/6680f57f595146bdb69bbaa0e336297a74b33acf/src/module.indexer/indexer.spec/oracle.appointed.token.currency.spec.ts#L247

2021-07-28 04:51 UTC, monstrobishi commented on src/module.indexer/error.ts
> +    super(`the ${item} length is not valid`)
Cover these error conditions

2021-07-28 04:54 UTC, monstrobishi commented on src/module.indexer/model/poolpair.ts
> +          if (Object.keys(rpcPoolPair).length !== 1) throw new RpcItemLengthError('poolpair')
Let's try to have brackets even on single line if statements otherwise it's error prone

2021-07-28 04:55 UTC, monstrobishi commented on src/module.indexer/model/poolpair.ts
> +    return `${tokenA[tokenAId].symbol}-${tokenB[tokenBId].symbol}`
This isn't a reliable way to construct the symbol unfortunately, as it can be set to anything during `createpoolpair`

2021-07-28 04:56 UTC, monstrobishi commented on src/module.indexer/model/poolpair.ts
> +    return `${tokenA[tokenAId].symbol}-${tokenB[tokenBId].symbol}`
If you need to find a certain poolpair containing tokens A and B, then loop through available poolpairs and check the tokenA and tokenB properties, or use a partition key of the tokens

2021-07-28 04:57 UTC, monstrobishi commented on src/module.indexer/model/poolpair.ts
> +    return `${tokenA[tokenAId].symbol}-${tokenB[tokenBId].symbol}`
ignore previous comments, I see now this is just to mimic rpc default behaviour

2021-07-28 04:59 UTC, monstrobishi commented on src/module.indexer/indexer.spec/poolpair.spec.ts
> +}
Test poolpair with custom `pairSymbol`

2021-07-29 10:29 UTC, canonbrother commented on src/module.indexer/model/poolpair.ts
> +    return `${tokenA[tokenAId].symbol}-${tokenB[tokenBId].symbol}`
i just see this comment after added the changes :sweat:

2021-11-22 03:01 UTC, monstrobishi commented
Closing this as we already have the functionality in main

2021-11-22 03:01 UTC, closed without merging