Made collateral address optional if it is undefined.
DeFiCh/whale pull request #224
Opened 2021-07-10 11:31 UTC by siradji

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Removed undefined data from token controller 
#### Which issue(s) does this PR fixes?:

Fixes #206 

#### Additional comments?:

2021-07-12 06:28 UTC, fuxingloh requested changes

2021-07-12 06:28 UTC, fuxingloh commented on src/module.api/token.controller.ts
> +    ...(!(tokenInfo.collateralAddress === '') && { collateralAddress: tokenInfo.collateralAddress })
```suggestion
    collateralAddress: tokenInfo.collateralAddress !== '' ? tokenInfo.collateralAddress : undefined
```

I think it's cleaner if you write it like this, instead of object restructuring and structuring.

2021-07-12 07:37 UTC, fuxingloh commented
fix test to assert undefined for test

2021-07-12 08:02 UTC, siradji commented
> fix test to assert undefined for test

@fuxingloh , it is done.

2021-07-12 08:07 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(result[0].collateralAddress).toBeUndefined()
In my opinion, you shouldn't check specifically if a value is undefined or not like in line `37`
We can assume the value is undefined if it is not exists in the result of the expect in line `38`

2021-07-12 08:10 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(result[0].collateralAddress).toBeUndefined()
In my opinion, you shouldn't check specifically if a value is undefined or not like in line 37
We can assume the value is undefined if it is not exists in the result of the expect in line 38

@fuxingloh what do you think?

2021-07-12 09:30 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(result[0].collateralAddress).toBeUndefined()
yeah jimmy

2021-07-12 13:11 UTC, siradji commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(result[0].collateralAddress).toBeUndefined()
Done

2021-07-12 15:23 UTC, jingyi2811 approved these changes

2021-07-13 03:31 UTC, fuxingloh approved these changes

2021-07-13 03:31 UTC, merged