added poolpairs.controller.ts
DeFiCh/whale pull request #24
Opened 2021-05-02 13:40 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Implements poolpairs.controller.ts that exposes POST /v1/network/poolpairs for creating, getting and listing pool pairs, adding pool liquidity and listing pool shares

2021-05-03 03:26 UTC, fuxingloh requested changes
Requested an initial set of changes, will review other parts later.

2021-05-03 03:26 UTC, fuxingloh commented on README.md
> +[![TS-Standard](https://badgen.net/badge/code%20style/ts-standard)](https://github.com/standard/ts-standard)
🧐

2021-05-03 03:26 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +  }
We don't need createPoolPair for DeFi whale as it will be running a stateless, wallet-less node where the only mutating function is it can submit raw txn. In another words, only GET operations.

2021-05-03 03:26 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +  }
I believe https://github.com/typestack/class-transformer can do all these, which is part of this package.

You can remap Number, and e.g. can fail if `start` and `limit` is negative. You can make it strict and fail exceptionally if any validation fail.

2021-05-03 03:26 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +  }
we don't need this too

2021-05-03 03:26 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +  @Get(':symbol')
Best to add the prefix seperator in front for better clarity of code.

`@Get('/:symbol')`

2021-05-03 07:22 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +}
We also need to follow a strict JSON in and out semantic for DeFi whale, since this is a REST service. I was looking at a [Stackoverflow](https://stackoverflow.com/questions/5543490/json-naming-convention-snake-case-camelcase-or-pascalcase) post comparing different types of naming convention. 

I think we can follow `snake_case` for all data transfer object (DTO, struct, POJO). An object that does not hold features but merely for use of transferring data between system. This allows consistency of thought where DTO class or interface have a very clean semantic. 

This will require the remapping of your JSON output, but I think this allows for cleaner implementations where consumer/producer contracts are clear and clean. Seeing as we will be owning the DeFi products (everything on top of blockchain) we can design a pattern of consistency into our core code.

> For reference https://github.com/DeFiCh/whale/blob/fuxingmodule/db-actor-address/src/module.database/models/block.ts (still WIP, this is part of a 3 module development I am working on now)

/cc @jingyi2811

2021-05-03 07:25 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +}
This also means you can look from a UI/UX building perspective and be selective about what data to transfer and not to.

You can remap DTO to fit a semantic that you think is clean for implementation.

2021-05-03 07:25 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +}
E.g. 
from
```ts
count_item: number
count_negative: number
```
to (as an example)
```ts
count: {
  item: number
  negative: number
}
```

2021-05-03 07:33 UTC, fuxingloh commented
As per the specs: https://github.com/DeFiCh/whale/issues/6

I think what I didn't mention was to provide a set of APIs for explorer/wallet/informatics to display relevant information. Bouncing ideas, not concrete but it should allow the UI implementation to just query and display without building complex query on the client-side. Hence to limit the query to a simple set of instruction, while the API service will perform them (complexly if required). Making it easier for dev usage.

#### Some thoughts:

GET v1/:network/poolpairs
- To get all poolpair with pagination

GET v1/:network/poolpairs/:id
- To get a specific poolpair

GET v1/:network/poolpairs/:id/swaps
- To see all the swaps in a pool pair with paginations

GET v1/:network/poolpairs/:id/liquidity
- To see all the add/remove liquidity in a pool pair
- To filter only add?
- To filter only remove?

GET v1/:network/poolpairs/:id/shares
- To see rich list?

2021-05-05 08:35 UTC, fuxingloh reviewed
some consideration you might want to take note of

2021-05-05 08:35 UTC, fuxingloh commented on src/main.ts
> +  app.useGlobalPipes(new ValidationPipe({ transform: true }))
I believe this provide the same feature 

https://github.com/DeFiCh/whale/blob/c098a07c647753fa6000c9790c8adae9aedc6576/src/module.api/index.ts#L16-L22

2021-05-05 08:35 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +}
you could import your types definitions from `jellyfish-api-core`

For example:
```ts
import { poolpair } from '@defichain/jellyfish-api-core'
let name: poolpair.CreatePoolPairMetadata
```

2021-05-12 10:26 UTC, fuxingloh requested changes

2021-05-12 10:26 UTC, fuxingloh commented on src/module.api/poolpairs.controller.ts
> +  async list (@Query(new PoolPairsQueryPipe()) filter?: PoolPairsFilter): Promise<PoolPairInfoDto[]> {
To follow the query specification in the recent pushed PR. Don't give the consumer the ability to query anything beyond one index. Lesser option is better.

2021-05-17 03:02 UTC, canonbrother commented
close this PR and re-work with new structure design

2021-05-17 03:02 UTC, closed without merging