Add interval indexers for Oracles
DeFiCh/whale pull request #283
Opened 2021-07-31 19:39 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

For performance and ease of implementation these interval indexers use the block height to estimate the interval, this also makes invalidation straightforward. This should be enough accuracy as they will mainly be used for graphing purposes.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-08-01 05:04 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
very tricky to include it within `set oracle data`. for bucket aggregation, you need to aggregate the entire bucket to get the average.

if there isn't a `set oracle data` within that block interval then you also will not have it saved as a result.

another anomaly of this design is it's hard to query data for displaying your need since the block time isn't a good y-coordinate due to the sporadic nature. made worst with 1008 block adjustment now

2021-08-01 05:26 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
Thanks for the feedback. I believe since this is happening after aggregation so the only case it would display no data is if there is no set Oracle within +- 1 hour? If that is an issue I could move this into a separate indexer and query the latest aggregate price from the mapper there.

Yes I did have concerns about block height as (X?) coordinate. If you believe that to be an issue I could check using:

`timeNow > lastEntryMedianTime + interval`

2021-08-01 05:41 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
Speaking of which, for `PriceAggregation` if there isn't a `SetOracleData` it will not create a new Aggregated entry. This might be problematic.

A separate indexer makes sense where you query aggregate price and bucket aggregate it, keeping the separation of concern intact.

2021-08-01 06:41 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
Regarding just `PriceAggregation`, I think this should work as it is already. As long as it does not make any entries when not live, the front end should simply request the latest aggregated price to display (Regardless of how old it is).

For interval it should also be ok, the frontend will use time to plot the axis, so the areas where there are no entries will simply be represented as a straight line with no data points.

2021-08-01 06:44 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
I have modified the indexers to use time as interval

2021-08-01 06:45 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
However this makes testing slightly difficult, as we have to mock the blocktimes somehow (Unless the test runs for an hour). Perhaps I should just manually put blocks into the mapper.

2021-08-01 08:44 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      for (const intervalMapper of this.intervalMappers) {
Would it make sense to do the following:
- Spin up a container and generate 100 blocks with one set oracle data per block
- List all blocks from block mapper
- Map all blocks and modify timestamp
- Start a new test app instance (or clear the existing block mapper)
- Pass in the modified list of blocks

2021-08-21 19:16 UTC, fuxingloh requested changes

2021-08-21 19:16 UTC, fuxingloh commented on packages/whale-api-client/src/api/prices.ts
> +    return await this.client.requestList('GET', `prices/${key}/${interval}/feed`, size, next)
```suggestion
    return await this.client.requestList('GET', `prices/${key}/feed/interval/${interval}`, size, next)
```

How about this

2021-08-21 19:16 UTC, fuxingloh commented on packages/whale-api-client/src/api/oracles.ts
> +}
```suggestion
```

Probably don't need this?

2021-08-21 19:16 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        await intervalMapper.put(aggregated)
We can't just do this for the interval price, we need to average all prices within the interval slice.

```ts
if exist

price = existing.price * existing.count + new.price
count += 1

else

price = new.price
count = 1
```

2021-08-23 08:51 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        await intervalMapper.put(aggregated)
I've updated as per your suggestion

2021-08-23 10:05 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        const prices = await this.aggregatedMapper.queryGt(`${token}-${currency}`, 5760, previous[0].sort)
will this include the `previous[0]` row? Should the `prices.reduce(..., previous[0].price)` start with it?

2021-08-23 10:05 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +          const averaged = prices.reduce((prev, curr): BigNumber => {
```suggestion
          const sum = prices.reduce((prev, curr): BigNumber => {
```

2021-08-23 10:05 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +          }, new BigNumber(0))
start with previous[0] price should make sense.

2021-08-24 06:49 UTC, fuxingloh requested changes

2021-08-24 06:49 UTC, fuxingloh commented on src/module.model/oracle.price.aggregated.interval.ts
> +const getOraclePriceAggregatedIntervalMapping = (interval: number): ModelMapping<OraclePriceAggregated> => ({
Instead of doing this why not have a single Model and Index by having the interval as part of the key.

It reduces the complexity of requiring us to create individual mapping.

2021-08-24 08:50 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
This is favorable, it spread out the workload. The largest interval has to do all the block when the last block come in.

@fuxingloh I think we do need definite starting point

block(t1), b(t2), b(t3), ..., b(t1 + 5min), b(t2 + 5min), ....

by doing this we will have 1 row per block, I think desired outcome is only have 1 row per interval.

2021-08-24 08:58 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
It is actually 1 row per interval right now, it only does put when interval is exceeded. But I get your point, the time slices should be based on the interval not when the block comes in. I'm wondering if we need a time-based indexing system (Schedular)? This would allow us to index things every X minutes rather than when a block comes in.

2021-08-24 08:58 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
Was replying to @ivan-zynesis just now

2021-08-24 09:56 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
> It is actually 1 row per interval right now

Yup, I did get that. Forward aggregate continuously as Fuxing suggested, could be quite tricky to keep track on the starting point.

2021-08-25 04:27 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
For script aggregation, it attempts to find a first. When the first isn't available it will create an empty record.

https://github.com/DeFiCh/whale/blob/bd8370ca648315bf6d6e1fd7193d6e1effa00a2d/src/module.indexer/model/script.aggregation.ts#L21-L27

2021-08-25 04:37 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
Let me clarify the forward aggregation method, you are referring to:
- Aggregate 5 minutes over all regular records
- Aggregate 10 minutes over the 5 minute records
- Aggregate 1 hour over the 10 minute records
- Aggregate 1 day over the 1 hour records

This is so that 1 day aggregation is not pulling up 2880 records correct?

2021-08-25 04:43 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
Nope,

Think of it from a data pipeline perspective ETL, MapReduce, etc

When new price aggregate comes in for 5 minutes pipeline.

1. Query previous in the 5 minutes index
2. Is the previous within the same 5 minutes bucket as now?
3. If so, aggregate forward via `count x price + price / count + 1`
4. Else, create new 5 minute bucket via `price=$, count=1`

When new price aggregate comes in for 10 minutes pipeline.

1. Query previous in the 10 minutes index
2. Is the previous within the same 10 minutes bucket as now?
3. If so, aggregate forward via `count x price + price / count + 1`
4. Else, create new 10 minute bucket via `price=$, count=1`

2021-08-25 04:59 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +        // Fetch all prices since the last interval
Ok I got it.

This would require a new data structure and model for storing the aggregation buckets correct?

The actual end result will be stored in another model with the interval as index as you suggested.

2021-08-27 07:24 UTC, canonbrother submitted a review, later dismissed

2021-08-31 07:03 UTC, fuxingloh requested changes

2021-08-31 07:03 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +      const previous = await this.aggregatedIntervalMapper.query(`${token}-${currency}-${interval}`, 2)
don't understand why you need to query 2, you should be able to query the one before and 
- decide whether you need to create a new bucket
- or average between the old bucket to form a new bucket replacing the old bucket

2021-09-26 14:14 UTC, fuxingloh requested changes

2021-09-26 14:14 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.interval.ts
> +  intervals: OracleIntervalSeconds[]
```suggestion
  intervals: OracleIntervalSeconds[] = [
      OracleIntervalSeconds.FIVE_MINUTES,
      OracleIntervalSeconds.TEN_MINUTES,
      OracleIntervalSeconds.ONE_HOUR,
      OracleIntervalSeconds.ONE_DAY
    ]
```

2021-09-26 14:14 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.interval.ts
> +    ]
```suggestion

```

2021-09-26 14:14 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.interval.ts
> +    if (previous[0].aggregated.count === 0) {
```suggestion
    if (previous[0].aggregated.count === 1) {
```

mistake?

2021-09-26 14:14 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.interval.ts
> +    if (previous[0].aggregated.count === 0) {
should put this function below `invalidate`, easier to follow the flow

2021-09-26 14:14 UTC, fuxingloh commented on src/module.model/oracle.price.aggregated.interval.ts
> +  }
should average `oracles.active/total` and `weightage` number for accuracy of interval data.

2021-10-03 08:09 UTC, fuxingloh commented
Some conflicts to resolve for this.

2021-10-04 15:08 UTC, fuxingloh submitted a review, later dismissed

2021-10-04 15:13 UTC, fuxingloh approved these changes

2021-10-04 15:21 UTC, merged