Add v1/:network/tokens related rpcs
DeFiCh/whale pull request #30
Opened 2021-05-04 04:50 UTC by jingyi2811

/kind feature

Add v1/:network/tokens related rpcs

2021-05-04 05:19 UTC, fuxingloh requested changes

2021-05-04 05:19 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +      throw new BadRequestException()
You need to test this aspect in E2E, all edge/validation cases must be tested.

2021-05-04 05:19 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +}
You need to implement this: https://github.com/DeFiCh/whale/pull/24#discussion_r624917549

2021-05-04 05:19 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +}
Whale service should never be a carbon copy of what the RPC throws out.

2021-05-04 05:19 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +  async get (@Param('id') id: string): Promise<TokenResult> {
This is a singular REST endpoint/contract, you put out one request for a `/:id` and expect one piece of data back. Not a map of thme.

Hence you should not return `Promise<TokenResult>`.
You need to return a singular `TokenInfo`, if the RPC does not conform to REST, you service need to.

2021-05-04 05:19 UTC, fuxingloh commented on __e2e__/tokens.e2e.ts
> +})
You need to setup at least another condition to test another token.

2021-05-04 05:19 UTC, fuxingloh commented on __e2e__/tokens.e2e.ts
> +describe('GET: /v1/regtest/tokens/DFI', () => {
1. Test all expected errors, validation, malformed, bad request
2. Test other endpoints not just one /:id

2021-05-05 09:52 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +}
should not need to export new interfaces for tests, can test blindly with `any` since your test will guarantee the values exists. as you will be asserting them. (remember typescript is compile-time type-safety only if you throw a JSON parsed value, it won't know the features of that parsed value)

2021-05-05 09:52 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +}
If you need to use interface from jellyfish you should import it, instead of copying it: https://github.com/DeFiCh/whale/pull/24#discussion_r626376928

2021-05-05 09:57 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +  })
hmm.. this is not quite right as the `ln: 162` might not 100% get triggered
jest doesn't have assert.fail (mocha) but jest can do expect(func()).throw(err)

2021-05-05 10:10 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +export interface TokenInfoDto {
ohh.. its duplicated.. just grab it from the controller

2021-05-08 08:18 UTC, fuxingloh requested changes

2021-05-08 08:18 UTC, fuxingloh commented on __e2e__/tokens.e2e.ts
> +}
rebase main, use the new `@defichain/testing` for testing

`npm i --save-dev @defichain/testing@next`

2021-05-09 15:56 UTC, jingyi2811 commented on src/module.api/tokens.controller.ts
> +    @Query(new TokenSizePipe()) size = '1000000000',
This value 1000000000 looks a bit funny. But, I was trying to select every tokens

2021-05-09 15:56 UTC, jingyi2811 commented on src/module.api/tokens.controller.ts
> +      return SliceResponse.of(tokenInfoDtos, limit, item => {
Not too sure whether my implementation is correct or not.

2021-05-09 15:58 UTC, jingyi2811 commented
Hope someone can review my code.

2021-05-12 07:00 UTC, canonbrother requested changes

2021-05-12 07:00 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +    @Query(new TokenSizePipe()) size = '1000000000',
why is that a string on size??

2021-05-12 07:00 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +    @Query(new TokenSizePipe()) size = '1000000000',
you don't need TokenSizePipe as that's no extra remap work
see https://docs.nestjs.com/techniques/validation

2021-05-12 07:00 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +    @Query(new TokenNextPipe()) next = '0'
same, don't need `TokenNextPipe` here

2021-05-12 07:00 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +    symbol_key: tokenInfo.symbolKey,
camelCase

2021-05-19 08:54 UTC, canonbrother requested changes
code looks cleaner a lot than before

2021-05-19 08:54 UTC, canonbrother commented on packages/whale-api-client/src/api/tokens.ts
> +  async get (size: number = 30, next?: string): Promise<ApiPagedResponse<TokenInfo>> {
list

2021-05-19 08:54 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +  async getId (@Param('id') id: string): Promise<TokenInfo> {
get

2021-05-19 08:54 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +    const data = await this.client.token.getToken(id)
do cache the token here

2021-05-19 08:54 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +  creationHeight: number
group the same category property
eg: 
```
creation: {
  tx,
  height,
}

2021-05-19 09:09 UTC, fuxingloh requested changes

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +      }).sort(a => Number.parseInt(a.id))
see AddressController for more info.

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +   * @param {string} id id/symbol/creationTx
let's not support `symbol` or `creationTx`, DeFi Whale don't need to follow Ain. We can keep the RESTful resources construct.

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +    const data = await this.client.token.getToken(id)
For cache, it is optional now, but a bonus if you implement it. Don't have to yet, you can create a ticket for it.

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +   * Returns information about tokens.
```suggestion
   * Paginate query tokens.
```

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +  })
these are ain/rpc design pattern, as mentioned, we only need to support RESTful API Design.

2021-05-19 09:09 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +    result.data.forEach(function (data) {
It will always be ordered as `[0]`, `[1]` use `[n]` to access array instead of forEach. ForEach will not be looped if empty hence your test is flawed when it return an empty array

2021-05-19 09:09 UTC, fuxingloh commented on packages/whale-api-client/src/api/tokens.ts
> +  async getId (id: string): Promise<TokenInfo> {
get

2021-05-19 09:09 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +      switch (data.symbol) {
same for this

2021-05-19 10:17 UTC, jingyi2811 commented on src/module.api/tokens.controller.ts
> +    const data = await this.client.token.getToken(id)
Will do this in another ticket

2021-05-19 13:16 UTC, jingyi2811 commented on src/module.api/tokens.controller.ts
> +    const data = await this.client.token.getToken(id)
Created a ticket for this. https://github.com/DeFiCh/whale/issues/85

2021-05-19 13:38 UTC, fuxingloh requested changes
much cleaner now, a few more things to address.

2021-05-19 13:38 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +    return mapTokenData('0', data[Object.keys(data)[0]])
`'0'`?

your assertions didn't catch this mistake

2021-05-19 13:38 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +    return mapTokenData('0', data[Object.keys(data)[0]])
How about if id is invalid?

2021-05-19 13:38 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +    })
add line breaks for code chunks like this

2021-05-19 13:38 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +  @Get('/')
Remove `'/'`

2021-05-19 13:38 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +          expect(data.symbol).toBe('DFI')
please look at the previous comment and format your test, this list is ordered.

2021-05-19 13:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +  })
Add another NotFound test

2021-05-19 13:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(data.symbol).toBe('DFI')
please test `data.id` as well.

2021-05-19 13:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +          expect(data.symbol).toBe('DFI')
read the previous comment about this. expecting a ordered list hence assertions should be oreded.

2021-05-19 13:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +  await createToken(container, 'DSWAP')
1. Add 1 more token with different conditions for testing
1. Add a LP token also.

2021-05-20 06:19 UTC, canonbrother requested changes
remove duplicate test

2021-05-20 06:19 UTC, canonbrother commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(forth.nextToken).toBe('3')
duplicated test
please adjust `size` as long as it covers  first -> next -> last

2021-05-20 06:19 UTC, canonbrother commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(data).toEqual({
test one will do unless that has diff condition to test

2021-05-20 06:22 UTC, fuxingloh requested changes

2021-05-20 06:22 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +      .toThrow('400 - BadRequest (/v1/regtest/tokens/4)')
This should be not found if it's not found, not bad request.

2021-05-20 06:22 UTC, fuxingloh commented on src/module.api/tokens.controller.ts
> +    const data = await this.client.token.getToken(id)
You need to catch the error to handle as NotFound.

2021-05-20 06:22 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +      .toThrow('Token not found')
and test for NotFoundException

2021-05-20 06:22 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +      .toThrow('Token not found')
see @canonbrother PR

2021-05-20 06:22 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +    const first = await controller.list({ size: 1 })
Same as e2e comment

2021-05-20 06:22 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +    let data = result.data[0]
same as e2e comment.

2021-05-20 09:05 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +      .toThrow('400 - BadRequest (/v1/regtest/tokens/4)')
<img width="796" alt="Screenshot 2021-05-20 at 5 04 14 PM" src="https://user-images.githubusercontent.com/7101806/118951167-73d81380-b98d-11eb-934f-df9e32ab3a9e.png">

Webster was able to catch WhaleApiException but I could not. Kindly advise. Thanks.

2021-05-20 09:07 UTC, jingyi2811 commented on src/module.api/tokens.controller.ts
> +      return mapTokenData(String(id), data[Object.keys(data)[0]])
Casting to String because ParseIntPipe change the id to integer

2021-05-20 09:26 UTC, fuxingloh requested changes
1 minor change

2021-05-20 09:26 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(last.nextToken).toBeUndefined()
you need to test that data is return in an order see in `test.ts`, you did it for `spec.ts` but not in `test.ts`

2021-05-20 09:40 UTC, canonbrother requested changes

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +    expect(result.data[1]).toEqual({
remove the duplicated here

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +    })
should test the `controller.paginate` here

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DBTC token with id as param', async () => {
duplicated

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DETH token with id as param', async () => {
duplicated

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DBTC-DETH LP token with id as param', async () => {
duplicated

2021-05-20 09:40 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +      return mapTokenData(String(id), data[Object.keys(data)[0]])
`ParseIntPipe` won't convert string to int

2021-05-20 11:29 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(last.nextToken).toBeUndefined()
Ya, I purposely removed it. Thinking that I had already verified in spec. Let me add it back.

2021-05-20 11:32 UTC, jingyi2811 commented on src/module.api/tokens.controller.spec.ts
> +    })
But the problem is, all other controller.spec files do not have the paginate keywords

2021-05-20 11:41 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/tokens.test.ts
> +    expect(last.nextToken).toBeUndefined()
this is because order might change when serialized, this just e2e test this behavior that a correct data structure is used.

2021-05-20 11:42 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DBTC-DETH LP token with id as param', async () => {
We can keep LP token

2021-05-20 11:42 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +    })
likely type from @canonbrother since this is spec.ts

2021-05-20 11:50 UTC, jingyi2811 commented
ParseIntPipe won't convert string to int

Nvm, I follow your implementation in poolpair. You expect an integer here.

<img width="554" alt="Screenshot 2021-05-20 at 7 46 10 PM" src="https://user-images.githubusercontent.com/7101806/118973714-8b6ec680-b9a4-11eb-93de-84043851e05e.png">

2021-05-20 11:52 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DETH token with id as param', async () => {
we can keep this since it's added

2021-05-20 11:52 UTC, fuxingloh commented on src/module.api/tokens.controller.spec.ts
> +  it('should return DBTC token with id as param', async () => {
we can keep this since it's added

2021-05-20 11:54 UTC, fuxingloh commented
> ParseIntPipe won't convert string to int
> 
> Nvm, I follow your implementation in poolpair. You expect an integer here.
> 
> <img alt="Screenshot 2021-05-20 at 7 46 10 PM" width="554" src="https://user-images.githubusercontent.com/7101806/118973714-8b6ec680-b9a4-11eb-93de-84043851e05e.png">

If this is the case, write a test to assert what it should be.

2021-05-20 11:59 UTC, canonbrother commented on src/module.api/tokens.controller.spec.ts
> +    })
yea my bad.. seeing it wrongly

2021-05-20 12:34 UTC, canonbrother commented on src/module.api/tokens.controller.ts
> +      return mapTokenData(String(id), data[Object.keys(data)[0]])
tested on the `cast` and i was misunderstand `ParseIntPipep` previously as i did check the id type inside scope

2021-05-20 12:51 UTC, jingyi2811 commented on src/module.api/tokens.controller.spec.ts
> +    expect(result.data[1]).toEqual({
I will keep this too

2021-05-20 13:02 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
>      expect(response).toEqual({
I changed to toStrictEqual just now, however it raised testing error, and hence,  I reverted back the code. I will do this tomorrow again.

2021-05-20 13:16 UTC, fuxingloh approved these changes

2021-05-20 14:08 UTC, canonbrother approved these changes

2021-05-20 15:43 UTC, merged