Add basic APR calculation to `poolpair-controller`
DeFiCh/whale pull request #323
Opened 2021-08-05 08:32 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Add basic APR calculation to `poolpair-controller`

#### Which issue(s) does this PR fixes?:

Fixes #307

#### Additional comments?:

2021-08-05 11:03 UTC, jingyi2811 approved these changes

2021-08-05 14:29 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +function mapPoolPair (id: string, info: PoolPairInfo, totalLiquidityUsd?: BigNumber,
should leave the function below, since `@Controller` is contextually more important.

2021-08-05 14:35 UTC, fuxingloh requested changes

2021-08-05 14:35 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +    }
```suggestion
    return {
      reward: reward,
      total: reward
    }
```

2021-08-05 14:35 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +    return new BigNumber(rpcResult.LP_DAILY_DFI_REWARD)
cache this function

2021-08-05 14:35 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +    const dfiPriceUsdt: BigNumber = await this.getUSDT_PER_DFI() ?? new BigNumber(0)
APR is in USDT?

shouldn't it be a percent relative to pool size?

2021-08-06 09:40 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +    const dfiPriceUsdt: BigNumber = await this.getUSDT_PER_DFI() ?? new BigNumber(0)
It is a percentage, USD price is needed for rewards in usd over tvl in usd

2021-08-06 09:41 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +    const dfiPriceUsdt: BigNumber = await this.getUSDT_PER_DFI() ?? new BigNumber(0)
Now that you mention something looks off, it's missing the division! Good spotting

2021-08-06 12:24 UTC, fuxingloh requested changes

2021-08-06 12:24 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    apr: apr ?? { total: 0, reward: 0 }
should default to `undefined` and make it optional, similar to `totalLiquidity.usd` better if we throw error than display results wrongly.

2021-08-06 12:45 UTC, fuxingloh commented on packages/whale-api-client/src/api/poolpairs.ts
> +  apr: { total: number, reward: number } | undefined
```suggestion
  apr?: { total: number, reward: number }
```

2021-08-06 12:55 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +        const [reward] = customReward.split('@')
The right side of the split doesn't matter?

2021-08-06 13:08 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +        const [reward] = customReward.split('@')
The existing logic only handles DFI rewards (As it relies on DFI usd price, and rewards are expected to stay in DFI for the foreseable future).

I've added an assertion to make this more clear, and catch it if it becomes an issue in future.

2021-08-06 14:01 UTC, fuxingloh commented
- Refactor code smell
- Refactor types to be cleaner by referencing instead of declaring
- Certain errors should not fail but return undefined
- Should return fractional numbers instead of percentages 
- Updated ttl to 60 minutes since get daily dfi reward hardly ever changes

2021-08-06 14:45 UTC, fuxingloh approved these changes

2021-08-06 14:45 UTC, merged