Update mn resp
DeFiCh/whale pull request #335
Opened 2021-08-11 05:21 UTC by canonbrother

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Added more completely mn data resp

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-08-11 05:37 UTC, fuxingloh requested changes

2021-08-11 05:41 UTC, canonbrother commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
ohh.. because i'm thinking to display all mn and own mn in mobile
so you mean just list all mns will do?
what about resignmn() in mobile if doesn't know which one is own mn??

2021-08-11 05:46 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
Yeah, masternode implementation on mobile is more of creating and delegating because the operations of nodes are delegated out to somewhere else to manage.

On the topic of resignmn(), we need a method to list mine... are there any existing API that allows owner address lookup? Or else we need to index them.

2021-08-11 07:08 UTC, canonbrother commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
> Yeah, masternode implementation on mobile is more of creating and delegating because the operations of nodes are delegated out to somewhere else to manage.

i got confused on the `mine`, yea we don't need `isMine` but `local`??
![image](https://user-images.githubusercontent.com/8097901/128982581-cfeef591-582d-4a72-82bc-765963a6ea52.png)
reference: https://marvelapp.com/prototype/5g9bcj4/screen/65368535

> On the topic of resignmn(), we need a method to list mine... are there any existing API that allows owner address lookup? Or else we need to index them.
in mobile side, list all mns, find own mn filtered by `wallet.get(0).getAddress()` (ownerAddress)

2021-08-11 07:39 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
We need an API to filter e.g. `/address/:.../masternodes` querying 8k masternode to find mine will DDOS the deployment.

2021-08-12 09:45 UTC, canonbrother commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
hmm.. is this needed to index the mn blocks (currently mn in whale is calling via jsonrpc)
```
id: masternodeId
partitionkey: address
sortKey: height
```

2021-08-12 09:46 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
Yeah, we need to index it

2021-08-12 09:47 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +  local: boolean
Ahmed is working on https://github.com/DeFiCh/whale/issues/325

But for individual data like yours, we need to index separately

2021-08-24 07:50 UTC, canonbrother commented
move to #349

2021-08-24 07:50 UTC, closed without merging