`create.masternode` `resign.masternode` `block.minted` indexers
DeFiCh/whale pull request #344
Opened 2021-08-17 10:16 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

This adds indexing of masternodes to whale. The masternode controller has been replaced with the indexed data. It works well in it's current state with any pre Euons Paya tx but will complain quietly if it indexes past that height.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-08-18 04:00 UTC, canonbrother commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
something like this
```suggestion
        timelock: data.timelock || 0,
```

2021-08-18 04:01 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
there's no timelock in data

2021-08-18 04:03 UTC, canonbrother commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
heyy?? wait...

2021-08-18 04:05 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
that's what your PR is for. but I suggest we get this merged in first. I can submit a new PR with timelock indexing

2021-08-18 04:05 UTC, canonbrother commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
we will have `data.timelock` in block after eunospaya, so here suggest to check if data.timelock === undefined (before eunospay) set to zero, else follow the timelock from block

2021-08-18 04:06 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.masternode.ts
> +        timelock: 0,
there's literally no timelock variable in the data object. this is typescript

2021-08-18 04:14 UTC, canonbrother commented on src/module.model/masternode.ts
> +export interface Masternode extends Model {
i think we need mn.state here

2021-08-18 04:15 UTC, monstrobishi commented on src/module.model/masternode.ts
> +export interface Masternode extends Model {
I had it originally then took it out. mn state should be inferred from creation and resign height rather than indexed

2021-08-18 04:16 UTC, monstrobishi commented on src/module.model/masternode.ts
> +export interface Masternode extends Model {
See the controller for more details

2021-08-18 04:16 UTC, canonbrother commented on src/module.model/masternode.ts
> +export interface Masternode extends Model {
some more TODO for my own about the tm1,2,3,4 after eunospaya mn merge
https://mydeficha.in/masternodes.php

2021-08-18 04:34 UTC, canonbrother approved these changes

2021-08-18 07:46 UTC, canonbrother submitted a review, later dismissed

2021-08-21 12:27 UTC, fuxingloh requested changes
Looks good to me, I requested the change because with `jellyfish:0.39.0` merged, there is a breaking change as webster fixed the issue you mentioned about it being the wrong field. in `create.masternode.ts`

The DfTx has also been renamed to `CreateMasternode` and `ResignMasternode` with the capital `N

2021-08-21 12:27 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.masternode.ts
> +      }
hmmm, the other Indexed data like `ScriptActivity` we keep it network agonistic, maybe it makes more sense to resolve them at query time instead of storing them at the resolved state

> Up to you if you want to make the change, but this PR is good. Since we are going to consolidate jellyfish sub-projects into one, we can change them in the future.

2021-08-21 12:38 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.masternode.ts
> +      }
Ok so I can store it as pubkeyhash and resolve in the service. That sounds good. Script resolution shouldn't be a huge performance bottleneck on request right? No need to cache?

2021-08-21 12:57 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.masternode.ts
> +      }
Nope, we don't need to cache, it's a fairly simple deterministic code. Way faster than `JSON.stringify()`

2021-08-23 07:16 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.masternode.ts
> +      }
@fuxingloh I think I will stick to indexing the address as for operator I do have `data.operatorType` to go off but for owner I'm using `txn.vout[1].scriptPubKey.addresses[0]`.

Otherwise assuming `txn.vout[1].scriptPubKey.hex` is the pubkeyhash equivalent, is there a straightforward way to convert the owner pub key into an address without knowing the type down the line?

2021-08-23 07:38 UTC, monstrobishi commented
Will add timelock and tests here too

2021-08-23 08:56 UTC, fuxingloh requested changes

2021-08-23 08:56 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/masternodes.test.ts
> +        tx: '',
```suggestion
        tx: undefined,
```

How about we make it optional, make it less misleading

2021-08-23 08:56 UTC, fuxingloh commented on src/module.api/masternode.controller.ts
> +        tx: info.resignTx ?? '',
```suggestion
        tx: info.resignTx,
```

2021-08-23 08:58 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.masternode.ts
> +      }
Don't really understand what you mean. But I guess we can leave this as it is.

2021-08-23 09:33 UTC, ivan-zynesis reviewed
Looks good for DeFi Scan use.

Should we add extra indexing with owner address?

2021-08-23 09:35 UTC, monstrobishi commented
One moment gentleman, updating tests to reflect optional resign object

2021-08-23 09:36 UTC, monstrobishi commented
@ivan-zynesis I would like to see that in another PR

2021-08-23 09:41 UTC, fuxingloh requested changes

2021-08-23 09:41 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +    tx?: string
```suggestion
    tx:: string
```

2021-08-23 09:41 UTC, fuxingloh commented on packages/whale-api-client/src/api/masternodes.ts
> +    tx?: string
since now resign is optional, tx don't need to be

2021-08-23 11:41 UTC, ivan-zynesis approved these changes

2021-08-23 17:05 UTC, fuxingloh approved these changes

2021-08-23 17:05 UTC, merged