emission
DeFiCh/whale pull request #355
Opened 2021-08-23 08:08 UTC by siradji

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-08-24 20:05 UTC, siradji commented
@monstrobishi  need your advice on this.
https://github.com/DeFiCh/whale/blob/7463d7c4543dc0dd106f3b86d7f9d9f2a380cd5d/src/module.api/stats.controller.ts#L92-L132

2021-08-25 08:15 UTC, monstrobishi commented
@siradji 

For `eunosHeight` you should be able to get this from `getBlockchainInfo`, it's underneath the soft forks object (although it's technically a hard fork)

Remember to cache the RPC requests.

Remember that the emissions reduction period, etc could be different depending on the network. See the relevant values in chainparams.cpp: 

Mainnet: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L112
Testnet: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L330
Regtest: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L682

For the regtest value perhaps go with isJellyfish by default, as this is likely the one we are using for all of our test cases.

For the numbers involving DFI amounts switch to BigNumber, i.e.:
```
reductionAmount <= 0.0000000001
```
Could be
```
reductionAmount.lte(new BigNumber(0.00001))
```

We might also need 5 decimal 0 there as I changed above because the actual cpp code divides an integer by 10000 and checks if it's 0 (See: https://github.com/DeFiCh/ain/blob/master/src/validation.cpp#L1143) 
```
            CAmount reductionAmount;
            for (size_t i = reductions; i > 0; --i)
            {
                reductionAmount = (nSubsidy * consensusParams.emissionReductionAmount) / 100000;
                if (!reductionAmount) {
                    nSubsidy = 0;
                    break;
                }

                nSubsidy -= reductionAmount;
            }
```

Do check  https://github.com/DeFiCh/ain/blob/master/src/validation.cpp#L1143 and other relevant sections in the CPP.

Overall the logic looks good, do also expand the 33.33 * 0.01 to 0.3333 etc, for example, use BigNumbers where you can.

2021-08-25 08:19 UTC, monstrobishi commented
I say go with a good implementation first and use the tests to check it's validity, we should be able to verify the reduction is correct by testing against the first vOut of every block, once the reduction has gone through (In mainnet that's 2 weeks, i.e. 2880*14 blocks), where as in jellyfish regtest it's `32690` so much longer.

You might want to test against a regtest container with `isJellyFish` off actually as the reduction period is too long for practical testing (And use the non-jellyfish value in your implementaion).

2021-08-25 09:15 UTC, siradji commented
> @siradji 
> 
> 
> 
> For `eunosHeight` you should be able to get this from `getBlockchainInfo`, it's underneath the soft forks object (although it's technically a hard fork)
> 
> 
> 
> Remember to cache the RPC requests.
> 
> 
> 
> Remember that the emissions reduction period, etc could be different depending on the network. See the relevant values in chainparams.cpp: 
> 
> 
> 
> Mainnet: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L112
> 
> Testnet: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L330
> 
> Regtest: https://github.com/DeFiCh/ain/blob/master/src/chainparams.cpp#L682
> 
> 
> 
> For the regtest value perhaps go with isJellyfish by default, as this is likely the one we are using for all of our test cases.
> 
> 
> 
> For the numbers involving DFI amounts switch to BigNumber, i.e.:
> 
> ```
> 
> reductionAmount <= 0.0000000001
> 
> ```
> 
> Could be
> 
> ```
> 
> reductionAmount.lte(new BigNumber(0.00001))
> 
> ```
> 
> 
> 
> We might also need 5 decimal 0 there as I changed above because the actual cpp code divides an integer by 10000 and checks if it's 0 (See: https://github.com/DeFiCh/ain/blob/master/src/validation.cpp#L1143) 
> 
> ```
> 
>             CAmount reductionAmount;
> 
>             for (size_t i = reductions; i > 0; --i)
> 
>             {
> 
>                 reductionAmount = (nSubsidy * consensusParams.emissionReductionAmount) / 100000;
> 
>                 if (!reductionAmount) {
> 
>                     nSubsidy = 0;
> 
>                     break;
> 
>                 }
> 
> 
> 
>                 nSubsidy -= reductionAmount;
> 
>             }
> 
> ```
> 
> 
> 
> Do check  https://github.com/DeFiCh/ain/blob/master/src/validation.cpp#L1143 and other relevant sections in the CPP.
> 
> 
> 
> Overall the logic looks good, do also expand the 33.33 * 0.01 to 0.3333 etc, for example, use BigNumbers where you can.

Okay got it. Thanks!

2021-09-19 21:54 UTC, siradji commented
@monstrobishi , please review this again

2021-09-20 03:04 UTC, jingyi2811 commented on src/module.api/stats.controller.ts
> +      let reductionAmount = new BigNumber(0)
I don't think this line is necessary.

2021-09-20 03:05 UTC, jingyi2811 commented on src/module.api/stats.controller.ts
> +        reductionAmount = new BigNumber(blockSubsidy * emissionReductionAmount / 100000)
```suggestion
        let eductionAmount = new BigNumber(blockSubsidy * emissionReductionAmount / 100000)
```

2021-09-20 03:09 UTC, jingyi2811 commented on src/module.api/stats.controller.ts
> +        blockSubsidy -= reductionAmount.toNumber()
Is that better if you do the `toNumber` conversion outside the loop?

2021-09-20 03:15 UTC, monstrobishi commented
Would like to see some tests. If you need some guidance you can follow some the tests here:

https://github.com/DeFiCh/ain/blob/epic/loans/src/test/dip1fork_tests.cpp#L158

2021-09-20 03:19 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +      const emissionReductionAmount = 1658
I think use a BigNumber here, and remove the / 100000 (see below)

2021-09-20 03:19 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +      const emissionReductionAmount = 1658
And change to `1.658%`

2021-09-20 03:20 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +        reductionAmount = new BigNumber(blockSubsidy * emissionReductionAmount / 100000)
Just use the proper `1.658%` (I guess that's 0.01658) then remove the division by 100000 here

2021-09-20 03:21 UTC, monstrobishi commented
This seems like it's only calculating post-eunos height emissions, see the C++ logic also checks for the height and returns the old subsidy values if it's pre eunos height:

https://github.com/DeFiCh/ain/blob/20392165c633470fd5b4922ea075f4fb6bf5c23e/src/validation.cpp

2021-09-21 08:18 UTC, siradji commented on src/module.api/stats.controller.ts
> +      let reductionAmount = new BigNumber(0)
Yep. Removed

2021-09-21 08:35 UTC, monstrobishi commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +  function calculateCoinbaseRewards (blockReward: number, percentage: number): number {
Any reason these functions are inside the test itself, and not in the source code?

2021-09-21 08:36 UTC, monstrobishi commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +  function calculateCoinbaseRewards (blockReward: number, percentage: number): number {
Oh you are using to compare against returned values. Are you able to hardcode and test against a range of values like the cpp test I linked?

2021-09-21 09:43 UTC, siradji commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +  function calculateCoinbaseRewards (blockReward: number, percentage: number): number {
Yes, it works. I just feel testing the return values from the endpoint make more sense. Any reason why we should keep it hardcoded? just curious.

2021-09-22 08:14 UTC, monstrobishi commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +  function calculateCoinbaseRewards (blockReward: number, percentage: number): number {
Because having the same logic in two places isn't testing against anything. It's just running the same function twice with the same parameters. The hardcoded parameters from the CPP test at the bear minimum provide us a baseline to ensure our logic produces the same output as the CPP version with all of the integer precision calculations.

2021-09-22 08:15 UTC, monstrobishi commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +  function calculateCoinbaseRewards (blockReward: number, percentage: number): number {
Thanks resolving this convo

2021-09-22 08:19 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +    let eunosHeight = 0
```suggestion
    let eunosHeight = blockInfo?.softforks?.eunos?.height ?? 0
```

2021-09-22 08:21 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +      emission: await this.cachedGet('emission', this.getEmission.bind(this), 1000)
Maybe at a later stage `getEmission` can take a height instead, then at this level we pass the eunos height and burn info (caching those), but I'll approve for now

2021-09-22 08:21 UTC, monstrobishi submitted a review, later dismissed

2021-09-22 08:28 UTC, jingyi2811 commented on src/module.api/stats.controller.ts
> +    return blockSubsidy
I think this line can be removed.

2021-09-22 08:30 UTC, jingyi2811 commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +    return consensusParams.eunosHeight + (reductions * consensusParams.emissionReductionPeriod)
```suggestion
    return consensusParams.eunosHeight + reductions * consensusParams.emissionReductionPeriod
```

2021-09-22 08:36 UTC, siradji commented on src/module.api/stats.controller.ts
> +    return blockSubsidy
Yep. True ture

2021-09-22 08:38 UTC, siradji commented on src/module.api/stats.controller.ts
> +      emission: await this.cachedGet('emission', this.getEmission.bind(this), 1000)
Okay. I will open an issue for improvement after his gets merged.  Thanks for the assistance so far

2021-09-22 08:44 UTC, siradji commented
@monstrobishi , re-approval please.

2021-09-22 08:44 UTC, monstrobishi submitted a review, later dismissed

2021-09-22 08:45 UTC, jingyi2811 approved these changes

2021-09-23 05:03 UTC, fuxingloh requested changes

2021-09-23 05:03 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +export function getBlockSubsidy (eunosHeight: number, nHeight: number = 0): number {
Can this be implemented without loops?

2021-09-23 05:03 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    }
reduce complexity, remove the loops

2021-09-23 05:03 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      burned = burnInfo.amount.plus(burnInfo.emissionburn).plus(burnInfo.feeburn).toNumber()
won't be the burn be `1.0 - given rewards`, removing the need for getBurnInfo()

2021-09-23 08:25 UTC, siradji commented on src/module.api/stats.controller.ts
> +export function getBlockSubsidy (eunosHeight: number, nHeight: number = 0): number {
I do not think so as this is exactly how it is in the c++ side. @monstrobishi ??

2021-09-23 08:26 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +export function getBlockSubsidy (eunosHeight: number, nHeight: number = 0): number {
^ yes this is an exact replica of C++ implementation

2021-09-23 08:30 UTC, monstrobishi commented on src/module.api/stats.controller.ts
> +    }
yes this loop can be unrolled, its just looping over all the types

2021-09-26 13:14 UTC, fuxingloh requested changes

2021-09-26 13:14 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +import { getBlockSubsidy } from '@src/module.api/stats.controller'
```suggestion
```

don't import controller logic for e2e tests, keep your testing code static as the numbers should always be the same at the same block height

2021-09-26 13:14 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      burned = burnInfo.amount.plus(burnInfo.emissionburn).plus(burnInfo.feeburn).toNumber()
@siradji is this true?

2021-09-26 13:14 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    }
unnecessary redeclaration, you can compress this

2021-09-26 13:14 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +export function getBlockSubsidy (eunosHeight: number, nHeight: number = 0): number {
is there a way to write this without loops? (regardless of how C++ implement it)

2021-09-27 08:54 UTC, siradji commented on src/module.api/stats.controller.ts
> +      burned = burnInfo.amount.plus(burnInfo.emissionburn).plus(burnInfo.feeburn).toNumber()
no i don't think so 1.0 - anything will be a negative.

2021-09-27 08:55 UTC, siradji commented on src/module.api/stats.controller.ts
> +export function getBlockSubsidy (eunosHeight: number, nHeight: number = 0): number {
Let me study the code more and understand it better. Perhaps it is possible

2021-09-27 19:51 UTC, siradji commented
https://github.com/DeFiCh/whale/pull/355#discussion_r716202486

@fuxingloh it is true. The burned total is the amount  + feeburn. 
https://github.com/DeFiCh/whale/blob/9698a05ebecdb86c74f6521c6d14b1017a0d56ad/src/module.api/stats.controller.ts#L83-L91

2021-09-27 20:06 UTC, siradji commented
https://github.com/DeFiCh/whale/pull/355#discussion_r716202914

@fuxingloh , i checked and to my understanding i can find an alternative. perhaps @monstrobishi you can put your input here.

2021-09-28 19:54 UTC, siradji commented
@fuxingloh , i need to get this merged before i can continue working on the supply data.

2021-10-06 08:28 UTC, fuxingloh approved these changes

2021-10-06 08:29 UTC, merged