Index `create.token`
DeFiCh/whale pull request #373
Opened 2021-08-31 07:32 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

This indexes `create.token`. Initially I wanted to index `update.token` too (Hence the branch name), but this would require a secondary index as `update.token` uses the txid as a reference, so I decided that was out of scope.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-08-31 07:50 UTC, fuxingloh commented on src/module.model/token.ts
> +export const DCT_ID_START = 128
Well, this number is way too low LOL

2021-09-26 14:22 UTC, fuxingloh requested changes

2021-09-26 14:22 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.token.ts
> +      // Default to 1 as 0 is reserved for DFI
we should index DFI token on indexGenesis method.

2021-09-26 14:22 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.token.ts
> +      : await this.tokenMapper.getLatestDST()
you should separate your logic into `if (isDat) {} else {}` with 2 major code blocks, instead of conditionally running your logic in multiple code blocks. Easier to read and maintain long term.

2021-09-27 09:57 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.token.ts
> +      // Default to 1 as 0 is reserved for DFI
Oh yes I had this in monstrobishi/index-poolpairs, will cherry pick over

2021-09-27 13:45 UTC, fuxingloh requested changes

2021-09-27 13:45 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.token.ts
> +        return 1
throw error?

2021-09-28 07:01 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.token.ts
> +        return 1
Oh yes, since DFI is already indexed?

2021-09-28 07:23 UTC, fuxingloh approved these changes

2021-09-28 07:23 UTC, merged