`create.poolpair` `update.poolpair`
DeFiCh/whale pull request #375
Opened 2021-08-31 13:04 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Index create poolpair and update poolpair.

Note: TODO customRewards, ownerAddress, this is outside the scope of this ticket/PR

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-09-26 14:27 UTC, fuxingloh commented
I will review this after TokenIndexer has been merged.

2021-09-28 07:34 UTC, monstrobishi commented
Will fix conflicts

2021-09-28 18:38 UTC, fuxingloh requested changes
you should add invalidation tests

2021-09-28 18:38 UTC, fuxingloh commented on src/module.model/poolpair.ts
> +    height: number
Maybe should keep consistency and all the usual block details?

2021-09-28 18:38 UTC, fuxingloh commented on src/module.model/poolpair.token.ts
> +  }
same for this?

2021-09-28 18:38 UTC, fuxingloh commented on src/module.indexer/model/dftx/create.poolpair.ts
> +      await this.poolPairTokenMapper.delete(`${data.tokenA}-${data.tokenB}`)
```suggestion
      await this.poolPairTokenMapper.delete(`${data.tokenA}-${data.tokenB}-${tokenId}`)
```

2021-09-30 06:10 UTC, monstrobishi commented on src/module.indexer/model/dftx/create.poolpair.ts
> +      await this.poolPairTokenMapper.delete(`${data.tokenA}-${data.tokenB}`)
good spotting! actually should be `${data.tokenA}-${data.tokenB}-${tokenId - 1}`, fixed

2021-10-03 08:08 UTC, fuxingloh approved these changes

2021-10-03 08:08 UTC, merged