`/blocks` & `/transactions` improvement
DeFiCh/whale pull request #385
Opened 2021-09-09 08:33 UTC by monstrobishi

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

1. `blocks/:id/transactions` is not ordered by the first appearance in the block, currently it's sorted via txid. We need it to be sorted by the first appearance.
2. `/blocks` API `Block` model should include block reward, by checking the first transaction vout in the block.
3. `/transactions` API `Transaction` model should include total UTXO value out, the summing of all `vout` value.

See #383 https://github.com/DeFiCh/whale/issues/383

#### Which issue(s) does this PR fixes?:

Fixes #383

#### Additional comments?:

2021-09-09 08:38 UTC, fuxingloh requested changes

2021-09-09 08:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/blocks.test.ts
> +    expect(first[0]).toStrictEqual({ ...ExpectedBlock, reward: '33.33000000' })
I think we can add 33.33 into `ExpectedBlock`

2021-09-09 08:38 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/transaction.test.ts
> +      totalVOut: expect.any(String)
```suggestion
      totalVoutValue: expect.any(String)
```

2021-09-09 08:38 UTC, fuxingloh commented on packages/whale-api-client/src/api/transactions.ts
> +  totalVOut: string
```suggestion
  totalVoutValue: string
```

2021-09-09 08:38 UTC, fuxingloh commented on src/module.model/transaction.ts
> +  sort: string // --------------| height-order
do we need height, maybe order will do

2021-09-09 08:38 UTC, fuxingloh commented on src/module.indexer/model/transaction.ts
> +      sort: `${block.hash}-${HexEncoder.encodeHeight(order)}`,
don't think we should add `block.hash` since it's already sort of block.hash

2021-09-09 08:48 UTC, monstrobishi commented on src/module.indexer/model/transaction.ts
> +      sort: `${block.hash}-${HexEncoder.encodeHeight(order)}`,
I think it's needed because block hash is the partition key. If I try to query without prepending block hash I get no output

2021-09-10 04:19 UTC, fuxingloh requested changes

2021-09-10 04:19 UTC, fuxingloh commented on src/module.api/transaction.controller.ts
> +function mapTransaction (tx: ModelTransaction): Transaction {
does this remove, `sort`? we should just include it

2021-09-10 04:19 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +function mapBlock (block: ModelBlock): Block {
I don't think we need this?

2021-09-10 04:19 UTC, fuxingloh commented on src/module.indexer/model/transaction.ts
> +      sort: `${block.hash}-${HexEncoder.encodeHeight(order)}`,
we don't need it because the sort is part of the block.hash partition key,

1. txn 0: [block.hash: 64len, order: 0]
2. txn 1: [block.hash: 64len, order: 1]

2021-09-10 05:12 UTC, monstrobishi commented on src/module.api/block.controller.ts
> +function mapBlock (block: ModelBlock): Block {
Ok I thought it would be cleaner to explicity map whale Block into whale api client Block, but I can remove this

2021-09-10 05:14 UTC, monstrobishi commented on src/module.api/block.controller.ts
> +function mapBlock (block: ModelBlock): Block {
Ok I get my mistake now, the server side controller doesn't care or know about the API client structures. There are some existing instances where the controller returns API client structures though so we may want to go back and refactor those.

2021-09-10 06:22 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +function mapBlock (block: ModelBlock): Block {
Yeah, it's one of the ugly patterns we have now. Something to refactor when we migrate to jellyfish. Right now it's just nice we have a perfect match from client to server.

2021-09-13 13:48 UTC, fuxingloh commented
/kind feature because this is a breaking change

2021-09-13 13:59 UTC, fuxingloh requested changes
minor change request

2021-09-13 13:59 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +      return block
I think you can revert these changes, as it's already returning undefined if undefined?

2021-09-13 13:59 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +      return block
same for this?

2021-09-26 13:01 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +      return block
```suggestion
      return await this.blockMapper.getByHeight(height)
```

2021-09-26 13:01 UTC, fuxingloh commented on src/module.api/block.controller.ts
> +      return block
```suggestion
      return await this.blockMapper.getByHash(hashOrHeight)
```

2021-09-26 13:02 UTC, fuxingloh approved these changes

2021-09-26 13:09 UTC, merged