Added Listanchors endpoint
DeFiCh/whale pull request #389
Opened 2021-09-15 09:57 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #322 

#### Additional comments?:

2021-09-16 08:14 UTC, siradji commented
Docker buildx and sanity test are failing and i think it is related the new package i installed.  How do i resolve this?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/57817584/133576184-c823f3a5-3d03-4179-8f2e-b8bb86625394.png">

2021-09-16 08:52 UTC, siradji commented
@fuxingloh , I found out you want to add listanchors to masternode controller alone. I have already created a controller for anchors. Should i keep it or just go as planned?

2021-09-16 23:26 UTC, siradji commented
@fuxingloh could you give me some pointers on why my test is failing?

2021-09-20 10:50 UTC, fuxingloh commented on Dockerfile
> -RUN npm ci
remove this

2021-09-20 10:55 UTC, fuxingloh requested changes

2021-09-20 10:55 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +  async list (): Promise<AnchorData[]> {
missing pagination object

2021-09-20 10:55 UTC, fuxingloh commented on src/module.api/anchors.controller.e2e.ts
> +  await tGroup.stop()
`stopTestingApp` stops a container, tGroup also stops a container. It seems like you are attempting to stop an already stopped container.

try:
- app.stop
- group.stop

2021-09-21 12:03 UTC, siradji commented on src/module.api/anchors.controller.ts
> +  async list (): Promise<AnchorData[]> {
@fuxingloh , listanchors rpc does not supports pagination. I believe there is way around this on the whale side. Could you point me to that?

2021-09-22 12:34 UTC, siradji commented on Dockerfile
> -RUN npm ci
I changed it but got a build error. Another way to solve this is to commit my package-lock file.

2021-09-23 05:02 UTC, canonbrother commented on packages/whale-api-client/src/api/anchors.ts
> +
```suggestion
```

2021-09-26 13:51 UTC, fuxingloh requested changes

2021-09-26 13:51 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +    const result = await this.rpcClient.spv.listAnchors()
Missing pagination implementation via `maxBtcHeight`

2021-09-26 13:51 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +    anchorCreationHeight: anchors.anchorCreationHeight
```suggestion
    id: id.toString(),
    btc: {
      block: {
        height: anchors.btcBlockHeight,
        hash: anchors.btcBlockHash,
      },
      txn: {
        hash: anchors.btcTxHash
      },
      confirmations: anchors.confirmations,
    },
    dfi: {
      block: {
        height: anchors.defiBlockHeight,
        hash: anchors.defiBlockHash
      }
    },
    active: anchors.active,
    signatures: anchors.signatures,
    creationHeight: anchors.anchorCreationHeight,
    rewardAddress: anchors.rewardAddress,
    previousAnchor: anchors.previousAnchor,
```

2021-09-26 13:51 UTC, fuxingloh commented on packages/whale-api-client/src/api/anchors.ts
> +  async list (): Promise<AnchorData[]> {
pagination missing

2021-09-30 05:09 UTC, siradji commented on src/module.api/anchors.controller.ts
> +    const result = await this.rpcClient.spv.listAnchors()
I have implemented the pagination but i think it will suffice for now. We need to change it and find a better way in the long way

2021-09-30 07:11 UTC, siradji commented
@fuxingloh, pagination has been implemented via minBtcHeight and maxBtcHeight. I think it is not the most ideal way and we need some better in the future.

2021-09-30 07:34 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
this won't really work because anchors have gaps, let's hold onto this PR for now. We need anchors RPC to support size pagination @surangap

2021-09-30 08:13 UTC, siradji commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
Yeah that is what i have thought.

2021-09-30 08:38 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
Yeah, feel free to sound it upstream, if something is missing for your usecase.

2021-11-17 08:21 UTC, surangap commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
@fuxingloh so the problem here is that since anchors have gaps, even though query for `query.size` records, it will not retrieve that amount. it will take the input as `maxBtcHeight`

The internal implementation of `listanchors` RPC is a bit different from other `list*` RPCs. especially from where the data is retrieved. it retrieves from a multi-index container, not from the db.

But we can implement the pagination with `startBTCHeight, number of records` for sure.
Ref: https://github.com/DeFiCh/ain/blob/2baae1d961a72640cc1950bbaecc9b9537dbd521/src/masternodes/anchors.h#L220

2021-11-17 08:27 UTC, fuxingloh commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
Yup the problem with min/max height querying is you can't do size-based querying. If you attempt to do it like the above implementation, any large gaps will result in end of pagination. (min=next, max=next+size).

With start height + the number of records, is more deterministic as you can start searching from height with a max of n results. n[size] = the next "next token".

2021-11-17 08:38 UTC, surangap commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
https://github.com/DeFiCh/ain/issues/910

2021-12-22 23:00 UTC, siradji commented on src/module.api/anchors.controller.ts
> +      maxBtcHeight: query.next !== undefined ? Number(query.next) + query.size : query.size,
@surangap, how are we getting on this?

2022-01-23 09:59 UTC, fuxingloh commented
Close in favor of #719

2022-01-23 09:59 UTC, closed without merging