Added block difficulty to stat endpoint
DeFiCh/whale pull request #404
Opened 2021-09-24 09:11 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Added block difficulty to stat endpoint 

#### Which issue(s) does this PR fixes?:

Fixes #394 

#### Additional comments?:

2021-09-26 12:52 UTC, fuxingloh requested changes

2021-09-26 12:52 UTC, fuxingloh commented on packages/whale-api-client/src/api/stats.ts
> +  difficulty: number
```suggestion
  blockchain: {
    difficulty: number
  }
```

2021-09-27 03:49 UTC, fuxingloh requested changes

2021-09-27 03:49 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/stats.test.ts
> +      blockChain: {
```suggestion
      blockchain: {
```

2021-09-27 13:46 UTC, fuxingloh requested changes

2021-09-27 13:46 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +        difficulty: await this.cachedGet('difficulty', this.getDifficulty.bind(this), 300) ?? 0
On second thought, why not get the difficulty from `block` since it's provided by `const block = await this.blockMapper.getHighest()`

2021-09-27 19:46 UTC, siradji commented on src/module.api/stats.controller.ts
> +        difficulty: await this.cachedGet('difficulty', this.getDifficulty.bind(this), 300) ?? 0
Yeah that will cut some redundant code.

2021-09-28 07:22 UTC, fuxingloh approved these changes

2021-09-28 07:22 UTC, merged