active/next price indexer level
DeFiCh/whale pull request #433
Opened 2021-10-04 04:28 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

active/next price indexer level

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-10-04 06:33 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
It's refreshing every 120 blocks? It's not taking the 120 blocks prior to the current block?

2021-10-04 06:56 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
yes this is an attempt to mimic the C++ side implementation: 

https://github.com/DeFiCh/ain/pull/750/files#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98R3103

Every 120 blocks, active price becomes next price, and next price becomes the aggregated price

2021-10-04 06:57 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
this WIP I will move 120 into a constant later

2021-10-04 08:58 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
It's not about it being a constant.

This is because `block.height % 120 === 0` rule at `SetOracleData`, will only trigger every time there is a price with block%120 that come in the retrigger the next price update. If there isn't a DfTx for that block it will create gaps within the intervals.

2021-10-04 08:58 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
I believe C++ implementation is more on the RPC side? Hence it didn't matter?

2021-10-04 09:00 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
Easier if we use #432, but I favor the indexer level implementation because it allows history reading of active prices.

2021-10-04 09:46 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
Interesting, I was originally under the impression that OraclePriceAggregatedMapper was triggering on every block regardless, but looking at `mapPriceFeeds` I can see it only triggers when a relevant tx comes in.

The C++ implementation is not RPC side, you can see on the PR I linked above.

I got your answer that you favour the Indexer implementation so I will proceed with that. I will move the code so that it sits somewhere that is triggered every block rather than only when a `SetOracleData` comes in.

2021-10-04 10:04 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
Still just brainstorming here, I've implemented a slightly different approach, do you feel this works better? I can go ahead with tests/implementation details if this looks ok

2021-10-04 11:14 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
Also brainstorming here:

Slightly conflicted with the introduction of a new Model, I am leaning towards where we can have prices data only if there are prices activity.

2021-10-05 03:59 UTC, monstrobishi commented on src/module.indexer/model/dftx/set.oracle.data.ts
> +    if (block.height % 120 === 0) {
I'm open to suggestions, I think for now in order to accurately get active/next price behaviour we need to roll over every 120 blocks. Sure I can avoid writing to db if active/next price is the same, but the unique frequency of updates warrants a new model IMO.

2021-11-11 10:06 UTC, ivan-zynesis commented on src/module.indexer/model/active.price.ts
> +    if (block.height % BLOCK_INTERVAL !== 0) {
Has cpp changed this? I remember previously %BLOCK_INTERVAL just has to be a constant. And each ticker may have different start point.

2021-11-11 10:07 UTC, ivan-zynesis commented on src/module.indexer/model/active.price.ts
> +    if (block.height % BLOCK_INTERVAL !== 0) {
Has cpp changed this? I remember previously %BLOCK_INTERVAL just has to be a constant. And each ticker may have different start point.

2021-11-11 10:40 UTC, ivan-zynesis commented on src/module.indexer/model/active.price.ts
> +      sort: HexEncoder.encodeHeight(block.mediantime) + HexEncoder.encodeHeight(block.height)
Block time is complementary of height, I think can remove the medianTime here

2021-11-12 03:26 UTC, canonbrother commented on src/module.indexer/model/active.price.ts
> +    private readonly priceTickerMapper: PriceTickerMapper
is that good to have network differentiate the `BLOCK_INTERVAL` ??  
120 mainnet | 6 regtest
:thinking: 
```suggestion
    private readonly priceTickerMapper: PriceTickerMapper
    @Inject('NETWORK') protected readonly network: NetworkName
```

2021-11-12 03:27 UTC, canonbrother reviewed
overall good for me though

2021-11-12 06:55 UTC, monstrobishi commented on src/module.indexer/model/active.price.ts
> +    private readonly priceTickerMapper: PriceTickerMapper
any other suggestions?

2021-11-12 06:56 UTC, monstrobishi commented on src/module.indexer/model/active.price.ts
> +    private readonly priceTickerMapper: PriceTickerMapper
Oh right I got you, yes will integrate this

2021-11-12 06:56 UTC, monstrobishi commented on src/module.indexer/model/active.price.ts
> +    if (block.height % BLOCK_INTERVAL !== 0) {
Yes block height is from 0, that was changed once and then changed back again

2021-11-12 06:57 UTC, monstrobishi commented
@canonbrother @ivan-zynesis now that we upgraded jellyfish to 2.1.0 (This PR was submitted a while ago), I'll make a note to add some tests to compare with RPC results to be more confident

2021-11-12 06:58 UTC, monstrobishi commented on src/module.indexer/model/active.price.ts
> +      sort: HexEncoder.encodeHeight(block.mediantime) + HexEncoder.encodeHeight(block.height)
I'm not 100% certain there some blocks can still appear out of order

2021-11-13 22:01 UTC, fuxingloh commented on src/module.indexer/model/active.price.ts
> +      sort: HexEncoder.encodeHeight(block.mediantime) + HexEncoder.encodeHeight(block.height)
Blocks can appear out of order and by indexing with `median time` your ActivePrice will be out of order too

2021-11-13 22:20 UTC, fuxingloh requested changes

2021-11-13 22:20 UTC, fuxingloh commented on packages/whale-api-client/src/api/prices.ts
> +  next: {
```suggestion
  next?: {
```

2021-11-13 22:20 UTC, fuxingloh commented on src/module.model/oracle.price.active.ts
> +  sort: string // -------| medianTime-height
```suggestion
  sort: string // -------| height
```

2021-11-13 22:20 UTC, fuxingloh commented on src/module.indexer/model/active.price.ts
> +      sort: HexEncoder.encodeHeight(block.mediantime) + HexEncoder.encodeHeight(block.height)
```suggestion
      sort: HexEncoder.encodeHeight(block.height)
```

2021-11-13 22:20 UTC, fuxingloh commented on src/module.indexer/model/active.price.ts
> +    return aggregate?.oracles !== undefined &&
Checking that the oracle has recently published, the last aggregate can be taken from a long time ago since this is the latest data feed.

2021-11-14 00:34 UTC, merged

2021-11-14 13:39 UTC, fuxingloh commented on src/module.indexer/model/active.price.ts
> +      sort: HexEncoder.encodeHeight(block.mediantime) + HexEncoder.encodeHeight(block.height)
Was thinking about this further, since this entity is only created in every `120` block interval, the "appear out of order" is pretty irrelevant in this context. I guess using height is just for consistency.