Add GET v1/:network/mempool/transactions endpoint
DeFiCh/whale pull request #45
Opened 2021-05-08 16:50 UTC by jingyi2811

/kind feature

Add GET v1/:network/mempool/transactions endpoint

2021-05-08 16:51 UTC, jingyi2811 commented
Just added GET v1/:network/mempool/transactions.
Still left GET v1/:network/mempool

2021-05-08 17:37 UTC, fuxingloh requested changes
Changes to be made. 

However, mempool should return full transactions information instead of just `txid`. We can keep this PR as a draft for now. We need other critical parts merged in before this.

2021-05-08 17:37 UTC, fuxingloh commented on src/module.api/blockchain.controller.ts
> +export class BlockchainController {
Call it `MempoolController` since we are not providing all features in the blockchain RPC category.

2021-05-08 17:37 UTC, fuxingloh commented on __e2e__/blockchain.e2e.ts
> +describe('GET: /v1/regtest/mempooltransactions', () => {
`describe('GET: /v1/regtest/mempool/transactions', () => {`

2021-05-12 07:15 UTC, canonbrother requested changes

2021-05-12 07:15 UTC, canonbrother commented on src/module.api/mempool.controller.ts
> +  @Get('/transactions')
if using `/v1/:network/mempool` then just `@Get('/')` and func name could be getAll or list will do

2021-05-13 07:29 UTC, closed without merging