Index `createLoanScheme`
DeFiCh/whale pull request #560
Opened 2021-11-12 08:17 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Index `createLoanScheme`

#### Which issue(s) does this PR fixes?:

Fixes part of #541

#### Additional comments?:

2021-11-15 05:10 UTC, ivan-zynesis commented on src/module.model/loan.scheme.ts
> +
`getActiveLoanScheme (schemeId)` probably the most needed func, to get activated, search for a row activation height less than current height

2021-11-17 02:50 UTC, canonbrother commented on src/module.indexer/rpc.block.provider.ts
> +      await this.daemon.process(block)
@fuxingloh i need a daemon process so i put it here first.. will do better structure in near while

2021-11-17 03:37 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +        event: data.update.eq(0) ? LoanSchemeHistoryEvent.CREATE : LoanSchemeHistoryEvent.UPDATE,
CREATE or UPDATE is depend if the scheme ID existed instead of the `activation block`

2021-11-17 03:40 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +    const histories = await this.loanSchemeHistoryMapper.query(loanSchemeId, 1)
Another challenging part, it should restore to last "activated" one.

2021-11-17 03:42 UTC, ivan-zynesis commented on src/module.indexer/model/daemon.ts
> +export class Daemon {
What I mean by "daemon" simply saying it run on every block regardless of dftx type found in that raw block.
It still need `index` and `invalidate`, invalidate to undo the "delayed activation"

2021-11-17 03:48 UTC, fuxingloh commented on src/module.indexer/model/daemon.ts
> +export class Daemon {
What I hate about this is its performance implication since it's not linked to DfTx anymore. Hmmmm

2021-11-17 04:40 UTC, ivan-zynesis commented on src/module.indexer/model/daemon.ts
> +export class Daemon {
Agree, and this overhead is redundant more than 90% of the time. Another way is completely keep them in 1 table without separating history and normal, every row do come with height. `listLoanScheme` will have to be relayed to RPC like `listPoolPair`

2021-11-17 06:18 UTC, canonbrother commented on src/module.indexer/model/daemon.ts
> +export class Daemon {
great.. hmm.. yea.. this is my first naive solution.. my first thought was separate indexer and daemon functionality, i just parked the daemon inside the indexer runner temp..

2021-11-17 12:35 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +  }
@ivan-zynesis 
the easiest way
eg: 
```
const height = 128
const histories = [
  { activateAfterBlock: 135 },
  { activateAfterBlock: 130 },
  { activateAfterBlock: 120 },
  { activateAfterBlock: 110 }
]
const latestActive = histories.find(h => height > h.activateAfterBlock) // 120
```

2021-11-17 12:36 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +    const histories = await this.loanSchemeHistoryMapper.query(loanSchemeId, 1)
outdated
move to https://github.com/DeFiCh/whale/pull/560#discussion_r751197817

2021-11-17 12:41 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +        event: data.update.eq(0) ? LoanSchemeHistoryEvent.CREATE : LoanSchemeHistoryEvent.UPDATE,
i did it based on the ain LoanScheme design
if loanScheme.update == 0 -> CREATE else UPDATE

btw your suggestion is right too

2021-11-17 13:01 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +        event: data.update.eq(0) ? LoanSchemeHistoryEvent.CREATE : LoanSchemeHistoryEvent.UPDATE,
updated

2021-11-18 05:55 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    const list = await this.deferredLoanSchemeMapper.query(100)
```suggestion
    const list = await this.deferredLoanSchemeMapper.query(Number.MAX_SAFE_INTEGER)
```

2021-11-18 05:55 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    }
I would sort deferred actions by height in ascending when first item in the list doesn't meet the requirement, I would reject all in the list.

2021-11-18 05:55 UTC, fuxingloh commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    }
If you do this, it's better to paginate than get all at once since you will reject if conditions failed. But for this scheme setup, the implications are quite low due to low data traffic

2021-11-18 06:58 UTC, ivan-zynesis requested changes

2021-11-18 06:58 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +    const histories = await this.loanSchemeHistoryMapper.query(id, 50)
1. need while loop, could be last 50 all do not belongs to this scheme.
2. history length = 0 equal to delete scheme

2021-11-18 07:04 UTC, canonbrother commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    }
> I would sort deferred actions by height in ascending when first item in the list doesn't meet the requirement, I would reject all in the list.
the height doesn't matter as the deferLoanSchemeMapper just like `[s150, s200, s250, s300]`, i just pick and overwrite into loanSchemeMapper

> If you do this, it's better to paginate than get all at once since you will reject if conditions failed. But for this scheme setup, the implications are quite low due to low data traffic
yea.. pagination is required

2021-11-18 08:13 UTC, canonbrother commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    }
> I would sort deferred actions by height in ascending when first item in the list doesn't meet the requirement, I would reject all in the list.

hmm.. rethink about it

2021-11-18 09:32 UTC, canonbrother commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +    }
gonna remap `deferredLoanSchemeMapper` to support sort key on height

2021-11-19 17:14 UTC, jingyi2811 commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +  async invalidate (block: RawBlock, txns: Array<DfTxTransaction<LoanScheme>>): Promise<void> {
I am thinking is there a way to test this `invalidate` function. I believe you should delete from loanSchemeMapper as you add an entry in https://github.com/DeFiCh/whale/pull/560/files#diff-7ff60895c2f24c1c872034f35e84df4124d83935c496fe3758b28a0cadb3669aR32

2021-11-19 17:15 UTC, jingyi2811 commented on src/module.indexer/model/dftx/set.loan.scheme.spec.ts
> +          activateAfterBlock: '18446744073709551615',
If you want to use `'18446744073709551615'`, you probably should use `new BigNumber('0xffffffffffffffff')`. It looks much nicer

2021-11-19 17:18 UTC, jingyi2811 commented on src/module.indexer/model/dftx/set.loan.scheme.spec.ts
> +  if (activateAfterBlock !== undefined) {
You might not want to add activateAfterBlock if activateAfterBlock == new BigNumber('0xffffffffffffffff')

2021-11-19 17:24 UTC, jingyi2811 commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +  private async has (id: string): Promise<boolean> {
Not too sure you should add a function for this. If yes `has` maybe need to be replaced by a better name.

2021-11-19 17:24 UTC, jingyi2811 commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +    return !((await this.loanSchemeMapper.get(id)) == null)
```suggestion
    return (await this.loanSchemeMapper.get(id)) != null)
```

2021-11-19 17:26 UTC, jingyi2811 commented
Quite good. Left some comments

2021-11-22 02:42 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.spec.ts
> +  if (activateAfterBlock !== undefined) {
i don't what's wrong here.. its just a customize function on spec.ts

2021-11-22 02:44 UTC, canonbrother commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +  async invalidate (block: RawBlock, txns: Array<DfTxTransaction<LoanScheme>>): Promise<void> {
i have one previously but its removed.. anyway.. we don't a standardize way to test `invalidate` yet

2021-11-22 02:46 UTC, canonbrother commented on src/module.indexer/model/dftx/set.loan.scheme.ts
> +  private async has (id: string): Promise<boolean> {
please also give a suggestion as well if you have comment on it

2021-11-24 06:31 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +        await this.deferredLoanSchemeMapper.delete(each.id)
Cannot really hard delete them.

at `t10`: set with activate height = `t20`
fork happen between t10 and t20

indexing up to 21
invalidate back to 19
index block 20 again, the deferred action will be gone.

2021-11-24 06:34 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +  private async getPrevLoanScheme (id: string, height: number): Promise<LoanSchemeHistory | undefined> {
My strat in setCollateralToken indexer is add another index for `history` data and partitioned with `activated` or not, then can quickly retrieve last activated action.

2021-11-30 02:47 UTC, canonbrother commented on src/module.indexer/model/dftx/set.deferred.loan.scheme.ts
> +  private async getPrevLoanScheme (id: string, height: number): Promise<LoanSchemeHistory | undefined> {
@ivan-zynesis i know your strat but need it get approved first.. lemme follow the common implementation first.. its still not that bad

2022-03-08 08:44 UTC, closed without merging