Refactor `dftx.indexer`
DeFiCh/whale pull request #597
Opened 2021-11-18 08:00 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

This parses the block sequentially per transaction, allowing us to maintain parity with a regular node's blockchain indexing.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-11-18 18:05 UTC, monstrobishi commented
Another advantage to this system is that we no longer have to manually keep track of the module import order of indexers i.e. having AppointOracle before SetOracleData to ensure that an oracle database entry exists to set data on.

This is now "free" thanks to transaction order and upstream validation.

2021-11-19 00:53 UTC, fuxingloh commented
> Another advantage to this system is that we no longer have to manually keep track of the module import order of indexers i.e. having AppointOracle before SetOracleData to ensure that an oracle database entry exists to set data on.
> 
> This is now "free" thanks to transaction order and upstream validation.

This looks great!

2021-11-19 03:11 UTC, fuxingloh commented
My bad, an earlier lint merge caused a conflict

2021-11-19 04:18 UTC, monstrobishi commented
fixed the merge conflict @fuxingloh

2021-11-19 04:20 UTC, monstrobishi commented
oh the dftx active price fix was merged in, let me fix that too

2021-11-19 05:07 UTC, canonbrother reviewed
yea i'm good overall

2021-11-19 05:17 UTC, monstrobishi commented
Some funny stuff happening with the active price test after merge, will investigate first

2021-11-19 06:35 UTC, canonbrother submitted a review, later dismissed

2021-11-19 07:50 UTC, ivan-zynesis requested changes

2021-11-19 07:50 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/resign.masternode.ts
> +      await this.masternodeMapper.put({ ...mn, resignHeight: -1 })
I think this is bug before this PR, "reversed" `indexStats` needed here, increment count and TVL. Also in the invalidate createMasternode

2021-11-20 07:20 UTC, monstrobishi commented on src/module.indexer/model/dftx/resign.masternode.ts
> +      await this.masternodeMapper.put({ ...mn, resignHeight: -1 })
It's handled in `invalidateBlockStart`, this is a special case for the masternode indexer. Trust me it works fine it's in the unit tests.

2021-11-22 01:38 UTC, fuxingloh approved these changes
> quite a large and necessary change

It somehow makes things more complex and more simplified at the same time.

2021-11-22 01:39 UTC, fuxingloh commented on src/module.indexer/model/dftx/resign.masternode.ts
> +      await this.masternodeMapper.put({ ...mn, resignHeight: -1 })
Yeah, invalidateBlockStart reverse stats by removing the entire `indexStats` by block height

2021-11-22 02:01 UTC, merged