feat(whale-api): Add `froms` info on auction batch
DeFiCh/whale pull request #698
Opened 2022-01-11 17:15 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2022-02-21 06:26 UTC, fuxingloh commented
@canonbrother you mind fixing the conflicting files?

2022-02-21 06:28 UTC, fuxingloh commented
Do you also mind filling up the `What this PR does / why we need it:`, I am a little confused about what is this for. Would help with the clarity of the intent of this PR.

2022-02-21 06:29 UTC, canonbrother commented
> Do you also mind filling up the `What this PR does / why we need it:`, I am a little confused about what is this for. Would help with the clarity of the intent of this PR.

yea sure.. and lemme review my code again

2022-02-21 07:10 UTC, ivan-zynesis requested changes

2022-02-21 07:10 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +    const batchBid = await this.vaultAuctionBatchBidMapper.get(`${data.vaultId}-${data.index}`)
```suggestion
    const batchBid = await this.vaultAuctionBatchBidMapper.get(`${data.vaultId}-${auction-close-timestamp}-${data.index}`)
```

eg: 21st Jan liquidated, auctioned, collateral partially bided and back to active after 6 hours. 22nd Jan get liquidated again, same `${vaultId}-${batch-zero let say}`

2022-02-21 09:40 UTC, canonbrother commented on src/module.api/loan.vault.service.ts
> +      }
@ivan-zynesis 
bloody workaround

2022-02-21 09:42 UTC, canonbrother commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +    const batchBid = await this.vaultAuctionBatchBidMapper.get(`${data.vaultId}-${data.index}`)
that's no liquidationHeight for me
here's the fixes
https://github.com/DeFiCh/whale/pull/698#discussion_r810940543

2022-02-21 10:24 UTC, canonbrother commented on src/module.api/loan.vault.service.ts
> +        froms: bids.length > 0 ? bids.map(b => b.from) : [],
@ivan-zynesis 
new fixes

2022-02-21 12:10 UTC, fuxingloh commented
But if you are not the winner, you are always the loser in this scenario.

Am I correct to say that this PR highlights & exposes an API for a specific user auction history?

2022-02-21 13:37 UTC, fuxingloh commented
> > But if you are not the winner, you are always the loser in this scenario.
> > Am I correct to say that this PR highlights & exposes an API for a specific user auction history?
> 
> kind of.. but not a specific user auction history.. the data is for `listauction` api, its public one

I am thinking whether it makes sense to expose a `list address auction history` then we use that as a baseline instead?

2022-02-21 13:41 UTC, canonbrother commented
> list address auction histor

hmm.. we ady have that
```ts
@Get('/vaults/:id/auctions/:height/batches/:batchIndex/history')
  async listVaultAuctionHistory (
```
https://github.com/DeFiCh/whale/blob/f8b35e1ab48260d2ef56745035a96c125598d4e0/src/module.api/loan.controller.ts#L196-L197
we ady have that but this is little diff....

2022-02-22 04:17 UTC, fuxingloh commented on src/module.api/loan.vault.service.ts
> +        froms: bids.length > 0 ? bids.map(b => b.from) : [],
```suggestion
        froms: bids.map(b => b.from),
```

Since you are checking length, I assume you don't need this?

2022-02-22 04:20 UTC, fuxingloh commented on src/module.api/loan.auction.controller.e2e.ts
> +        expect(typeof batch.froms).toBe('object')
should check if there is an array with string?

2022-02-22 04:20 UTC, fuxingloh commented on src/module.api/loan.vault.service.ts
> +        froms: bids.length > 0 ? bids.map(b => b.from) : [],
I think we should also map this into human-readable address instead of leaving it as script.

2022-02-22 04:39 UTC, canonbrother commented on src/module.api/loan.auction.controller.e2e.ts
> +        expect(typeof batch.froms).toBe('object')
yep.. improved and added length checker
```ts
if (auction.vaultId === vaultId4) {
  expect(batch.froms.length).toStrictEqual(0)
} else {
  expect(batch.froms).toStrictEqual(
    expect.arrayContaining([expect.any(String)])
  )
  expect(batch.froms.length).toBeGreaterThan(0)
}
```

2022-02-22 08:21 UTC, fuxingloh commented
Some of the broken test in poolpair.test.ts has been fixed and refactored, you can remove them in your PR.

Planning to release this today too.

2022-02-22 09:52 UTC, fuxingloh commented on src/module.api/loan.vault.service.ts
> +        froms: bids.map(b => b.from),
Is this in hex as a script? 

If so, we need to convert into addresses via `@defichain/jellyfish-address` using:

https://github.com/DeFiCh/jellyfish/blob/9dfd4a006b69791c7b479272e9a24ab5c8144ec4/packages/jellyfish-address/src/script/index.ts#L105-L113

2022-02-22 09:54 UTC, fuxingloh commented on src/module.api/loan.vault.service.ts
> +        froms: bids.map(b => b.from),
For endpoint exposed, we need to expose the human-readable address to make it developer-friendly.

2022-02-22 10:55 UTC, canonbrother commented on src/module.api/loan.vault.service.ts
> +        froms: bids.map(b => b.from),
done.. i'm using `fromscripthex(hex, network).address`
```
// from
batch.froms:  [
      '001419dd9cb9d81d5c7f35c98b0c178b214de75c9198',
      '00148d125a7d98482871c3d061ae3aeb2b6f5c6c9fd1',
    ]
// to
batch.froms:  [
      'bcrt1q9lsvtmtcmpxvm0vkxcnzu2x89g4qgr3m3je4vz',
      'bcrt1q8nmrcjuaawyhqvrxhm03rl9s38n95jdyg7xjfm'
    ]
```

2022-02-22 15:38 UTC, fuxingloh commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +      from: from,
I think this will cause regression, we should only apply the remapping on the controller level.

@joeldavidw & @thedoublejay we can't merge this right?

2022-02-23 02:35 UTC, canonbrother commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +      from: from,
ohh.. wait.. lemme do a quick fix

2022-02-23 02:49 UTC, canonbrother commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +      from: from,
fixed https://github.com/DeFiCh/whale/pull/698/commits/a28d768d7c8d34b6819446620dfafe2c24473679 :pray:

2022-02-23 04:50 UTC, fuxingloh commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +    @Inject('NETWORK') private readonly network: NetworkName,
```suggestion
```

assuming we don't need this anymore

2022-02-23 05:05 UTC, ivan-zynesis submitted a review, later dismissed

2022-02-23 06:17 UTC, canonbrother commented on src/module.indexer/model/dftx/place.auction.bid.ts
> +    @Inject('NETWORK') private readonly network: NetworkName,
gosh.. i missed it!!

2022-02-23 07:19 UTC, fuxingloh approved these changes

2022-02-23 07:19 UTC, merged