feat(indexer): `poolswap` "lite"
DeFiCh/whale pull request #713
Opened 2022-01-18 17:08 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Light implementation calculates volume and commission. Commission apr is added to total apr.

#### Which issue(s) does this PR fixes?:

Fixes #705

#### Additional comments?:

2022-01-24 04:36 UTC, canonbrother commented on src/module.indexer/model/dftx/create.poolpair.ts
> +      name: `${tokenA.symbol}-${tokenA.symbol} LP Token`,
```suggestion
      name: `${tokenA.symbol}-${tokenB.symbol} LP Token`,
```

2022-01-24 07:43 UTC, kodemon commented on src/module.indexer/model/dftx/compositeswap.ts
> +    if (poolIds.length === 0) {
`question:` wanted to gather some insights on value extraction in this method and other methods similar to it.

What is our thoughts around object spread, eg.

```ts
const { poolSwap, pools } = transaction.dftx.data
```

A quick secondary `nit:` is use of `poolIds` > `pools`. If `pools` is an array of objects, would `for (const pool of pools)` later in this function be more suitable?

I may be missing some underlying knowledge here so this is a shallow inquiry to expand my understanding. 🙏🏻

2022-01-24 07:52 UTC, canonbrother submitted a review, later dismissed

2022-01-24 07:54 UTC, kodemon approved these changes

2022-01-24 07:54 UTC, ivan-zynesis commented on src/module.api/poolpair.service.ts
> +      const dusdPair = await this.getPoolPair(token, 'DUSD')
can reverse the order, prioritize XXX-DUSD, avoid using any XXX-DFI, DFI-DUSD (I think do not exist at the moment)

2022-01-24 08:22 UTC, ivan-zynesis requested changes

2022-01-24 08:22 UTC, ivan-zynesis commented on src/module.api/poolpair.service.ts
> +        accum = accum.plus(amount.times(await this.getPriceForToken(swap.fromTokenId) ?? 0))
Can move the price retrieval out of for loop, in case cache expiry during summation.

2022-01-24 08:22 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/poolswap.ts
> +    await this.poolPairMapper.delete(`${poolPair.poolPairId}-${block.height}`)
```suggestion
    await this.poolSwapMapper.delete(`${poolPair.poolPairId}-${block.height}`)
```

2022-01-24 08:22 UTC, ivan-zynesis commented on src/module.indexer/model/dftx/poolswap.ts
> +
Can add a height check for found poolswap row

2022-01-24 09:32 UTC, monstrobishi commented on src/module.indexer/model/dftx/compositeswap.ts
> +    if (poolIds.length === 0) {
Actually that's fair, I'll keep in mind for my next PR, but I think this can get through

2022-01-24 09:35 UTC, monstrobishi commented on src/module.indexer/model/dftx/poolswap.ts
> +
This is looking for poolpair row not poolswap row

2022-01-24 09:38 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +        accum = accum.plus(amount.times(await this.getPriceForToken(swap.fromTokenId) ?? 0))
Was about to make this change, but unfortunately there is no way to know which token IDs we need prices for without looping over all the swaps.

In that case it would just be the same loop first without the `accum.plus`, which I don't think is a big computational load on modern machines.

I think leaving it as is would be for best.

2022-01-24 09:40 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +      const dusdPair = await this.getPoolPair(token, 'DUSD')
Can you elaborate on this, are you saying put the `TSLA-DUSD` test first?

2022-01-24 09:42 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +      const dusdPair = await this.getPoolPair(token, 'DUSD')
So is the rationale that there will be more XXX-DUSD pairs so we should check those first?

I'm not sure what the second part of the statement means

2022-01-24 09:43 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +      const dusdPair = await this.getPoolPair(token, 'DUSD')
Ok I've made this change

2022-01-24 09:46 UTC, kodemon commented on src/module.api/poolpair.service.ts
> +        accum = accum.plus(amount.times(await this.getPriceForToken(swap.fromTokenId) ?? 0))
In the future if we want to avoid sequential locks on price for token requests we can do a `Promise.all` to accumulate all swaps in parallel. But not sure if that is feasible in this particular instance or not, but definitely a future _potential_ optimization.

2022-01-24 15:48 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +        accum = accum.plus(amount.times(await this.getPriceForToken(swap.fromTokenId) ?? 0))
I find `Promise.all` not super useful in these accumulator style cases

2022-01-24 15:58 UTC, monstrobishi commented on src/module.indexer/model/dftx/poolswap.ts
> +
Ok I got what you mean, but since txid is part of the block I think it's fine for this case, we can revisit when we refactor into jellyfish

2022-01-25 03:53 UTC, ivan-zynesis approved these changes

2022-01-25 03:55 UTC, kodemon submitted a review, later dismissed

2022-01-26 04:03 UTC, canonbrother commented on src/module.api/poolpair.service.ts
> +        HexEncoder.encodeHeight(height - 2880))
ahh forgot this.. do we need diff main and reg blocksPerDay on query??

2022-01-26 06:22 UTC, fuxingloh reviewed
Did an initial review

2022-01-26 06:22 UTC, fuxingloh commented on src/module.indexer/model/dftx/compositeswap.ts
> +      await this.poolSwapIndexer.indexSwap(poolPair, poolSwap.fromTokenId, poolSwap.fromAmount, block, transaction.txn.txid)
There are multiple commissions after traversing through the composite path, should we `fromAmount * (1-commision)` to get a more accurate amount?

2022-01-26 06:22 UTC, fuxingloh commented on src/module.api/poolpair.service.ts
> +    const commission = info.commission.times(volume?.h24 ?? 0).times(365).div(totalLiquidityUSD)
This is quite a heavily called API in ocean, I would not implement this until we have the bucketed rolling aggregator for performance sake?

2022-01-26 06:26 UTC, ivan-zynesis commented on src/module.api/poolpair.service.ts
> +    const commission = info.commission.times(volume?.h24 ?? 0).times(365).div(totalLiquidityUSD)
Thought about this issue, but the implementation itself wouldn't be lite any more. Will a 8 to 24 hours cache durability work?

2022-01-26 10:48 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +    const commission = info.commission.times(volume?.h24 ?? 0).times(365).div(totalLiquidityUSD)
The db scan here shouldn't pose much of an issue, it's quite similar to how we're doing the oracle graphs. Plus it's cached.

2022-01-27 07:12 UTC, kodemon commented on src/module.indexer/model/dftx/compositeswap.ts
> +    let swapAmount
```suggestion
    let swapAmount: BigNumber
```
Since there is no type by reference here, should we explicitly add it here?

2022-01-27 10:26 UTC, ivan-zynesis commented on src/module.api/poolpair.service.ts
> +    const apr = yearlyUSD.div(totalLiquidityUSD)
Consider rename this to be not misleading, nothing to do with apr here.

2022-01-27 10:31 UTC, ivan-zynesis commented on src/module.api/poolpair.service.ts
> +    const commission = info.commission.times(volume?.h24 ?? 0).times(365).div(totalLiquidityUSD)
Hmm, * 365 can arguably a valid projection for a year, but I doubt should we do this. Need more opinions. @DeFiCh/jellyfish

2022-01-27 12:22 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +    const commission = info.commission.times(volume?.h24 ?? 0).times(365).div(totalLiquidityUSD)
This section of the code was removed

2022-01-31 02:34 UTC, monstrobishi commented on src/module.indexer/model/dftx/compositeswap.ts
> +      await this.poolPairMapper.delete(`${pool.id}-${block.height}`)
Wait how did I miss this, hold off until this is fixed

2022-01-31 02:41 UTC, monstrobishi commented on src/module.indexer/model/dftx/compositeswap.ts
> +      await this.poolPairMapper.delete(`${pool.id}-${block.height}`)
Ok that's fixed

2022-01-31 02:41 UTC, monstrobishi commented on src/module.api/poolpair.service.ts
> +        HexEncoder.encodeHeight(height - 2880))
This code section was removed

2022-01-31 12:26 UTC, kodemon approved these changes

2022-01-31 15:11 UTC, canonbrother submitted a review, later dismissed

2022-02-01 03:14 UTC, ivan-zynesis approved these changes

2022-02-08 10:13 UTC, fuxingloh commented on src/module.model/poolswap.ts
> +  sort: string // -------| height-txid
Would `height-txnNo` be better? Since `txid` is not ordered based on block order.

2022-02-09 06:39 UTC, fuxingloh approved these changes

2022-02-09 06:39 UTC, merged