feat(module-api): add `/stats/supply` API
DeFiCh/whale pull request #769
Opened 2022-02-10 08:03 UTC by canonbrother

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #310

#### Additional comments?:

2022-02-10 09:50 UTC, fuxingloh commented
This is block emission, we need supply get `getSupply` without emission data with burn information computed.

https://github.com/DeFiCh/whale/issues/310#issue-959067155

2022-02-10 09:50 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    const blockSubsidy = new BlockSubsidy()
Init once at class level.

2022-02-14 17:15 UTC, fuxingloh requested changes

2022-02-15 06:03 UTC, fuxingloh commented
Let me resolve the above issues, plan to release this today.

2022-02-15 06:05 UTC, canonbrother commented
> Let me resolve the above issues, plan to release this today.

ohh sorry.. didn't aware this is urgent
just done fixing the pg mig

2022-02-15 06:08 UTC, fuxingloh commented
> > Let me resolve the above issues, plan to release this today.
> 
> ohh sorry.. didn't aware this is urgent just done fixing the pg mig

No worries, I am almost done with it

2022-02-15 06:49 UTC, fuxingloh submitted a review, later dismissed

2022-02-15 07:30 UTC, ivan-zynesis requested changes

2022-02-15 07:30 UTC, ivan-zynesis commented on packages/whale-api-client/src/api/stats.ts
> +    address: number
Not a number

2022-02-15 07:30 UTC, ivan-zynesis commented on src/module.api/stats.controller.ts
> +    const burnInfo = await this.rpcClient.account.getBurnInfo()
```json
{
  "address": "8defichainBurnAddressXXXXXXXdRQkSm",
  "amount": 156002224.91060823,
  "tokens": [
    "7260.95539278@DFI",
    "6550.00000000@ETH",
    "2476.86380002@BTC",
    "14032000.00000000@USDT",
    "16820000.00000000@DOGE",
    "19051.00000000@LTC",
    "3131.00000000@BCH",
    "4850000.00000000@USDC"
  ],
  "feeburn": 231145,
  "auctionburn": 373343.59338137,
  "paybackburn": 24874737.59017394,
  "dexfeetokens": [
    "6.71301115@BTC",
    "169998.99260552@DUSD"
  ],
  "dfipaybackfee": 247081.92149736,
  "dfipaybacktokens": [
    "83392405.22988815@DUSD"
  ],
  "emissionburn": 76024798.59146397
}
```

a production value, since can see there is DUSD in `dfipaybacktokens` but not in `tokens` so we know `tokens` is not necessarily inclusive everything as a sum. Now I am not sure if `amount` does covered all utxo burnt either (eg `dfipaybackfee`), may want to double check with cpp team.

2022-02-15 07:33 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
@ivan-zynesis for address, it uses `burnInfo.amount.plus(getTokenBurn())` to get the address total burn amount.

UTXO and Token send to address

2022-02-15 07:35 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    const burnInfo = await this.rpcClient.account.getBurnInfo()
Hmm, maybe it's more accurate if we just get total balance from `8defichainBurnAddressXXXXXXXdRQkSm`

https://defiscan.live/address/8defichainBurnAddressXXXXXXXdRQkSm

2022-02-15 08:12 UTC, fuxingloh commented on packages/whale-api-client/src/api/stats.ts
> +    address: number
https://github.com/DeFiCh/whale/pull/769#discussion_r806525696

2022-02-15 08:24 UTC, ivan-zynesis commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
Wonder how all other burn (eg fee, auction) work? They are not sending to the same burn address?
I have no idea what is inclusive what is not now.

2022-02-15 08:27 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
They are sending to the burn address but upstream decided to break it down into different categories.

2022-02-15 08:28 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
Hence we just break it down into categories too.

2022-02-15 08:28 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    const burnInfo = await this.rpcClient.account.getBurnInfo()
For `dexfeetokens` and `dfipaybacktokens` it should only contain DFI tokens.

2022-02-15 08:29 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +    const burnInfo = await this.rpcClient.account.getBurnInfo()
I believe to leave it out of burn representation now until we have an applicable category for it.

2022-02-15 08:30 UTC, ivan-zynesis commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
Sounds like all the breakdown are subset of `tokens` and `amount`, the `total` shouldn't sum them up again right

2022-02-15 08:59 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
If I remember correctly, it used to be the subset but I think it's indexed separately wholely as its own category now.

2022-02-15 08:59 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
For reference:
https://defiscan.live/stats/burn vs https://defiscan.live/address/8defichainBurnAddressXXXXXXXdRQkSm

2022-02-15 09:13 UTC, ivan-zynesis commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
https://github.com/DeFiCh/whale/pull/769#discussion_r806527627
I think we should just use the balance then, it will work regardless how the BurnInfo calculated as long as the burn mechanic remained.

2022-02-15 14:02 UTC, fuxingloh commented on src/module.api/stats.controller.ts
> +      address: address.toNumber(),
I added a new method `getBurnedTotal` to just get total burned without relying on adding the categories together to make it future proof.

2022-02-15 14:04 UTC, ivan-zynesis approved these changes

2022-02-15 14:38 UTC, merged