added poolpairs.controller.ts
DeFiCh/whale pull request #83
Opened 2021-05-18 13:00 UTC by canonbrother

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #6 

#### Additional comments?:

2021-05-19 06:01 UTC, canonbrother commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +    const response = await client.poolpair.get('A-B')
not sure why here getting `Pool not found`

2021-05-19 07:12 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfo
We need to use `id: string` instead of `symbol` because when the operator feature kicks in there will be multiple competing PoolPair by different operators.

2021-05-19 07:13 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfo
Oh and don't use ConflictException for NotFound error.

2021-05-19 07:13 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfo
Conflict is should have but NotFound, NotFound is just NotFound.

2021-05-19 07:22 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +  }
Best to create another PR for this, separate this out because that first 2 endpoint is more urgent. We might want to have another PR to discuss how this should be implemented.

2021-05-19 07:22 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    creationHeight: poolPairInfo.creationHeight
I was thinking whether we can remap to something like this:

```ts
tokenA: {
  id: ,
  reserve: ,
  commission: ,
},
tokenB: {
...
}
```

And if `reserveA/reserveB` can be computed ownself, we can remove it.

2021-05-19 07:22 UTC, fuxingloh commented on src/module.api/cache/poolpair.info.cache.ts
> +    }
should separate this into another method, easier to read

2021-05-19 07:22 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +    const response = await client.poolpair.get('A-B')
Can't see why also, try running in debug mode?

2021-05-19 08:33 UTC, canonbrother commented on src/module.api/cache/poolpair.info.cache.ts
> +    }
hmm.. perhaps i make it one line
```
poolPairInfo = poolPairResult[ Object.keys(poolPairResult)[0] ]
```

2021-05-19 08:38 UTC, canonbrother commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfo
i actually follow this https://github.com/DeFiCh/whale/blob/8af244c50118436567ce340f316f0bdb7b49efeb/src/module.api/address.controller.ts#L40
oh yea i just copy paste it.. the message was wrong as well

yea `Conflict` is normally used for crashing with existing item right??

2021-05-19 09:12 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfo
For that use case because the token exists in your account, but cannot be found in the cache. Hence a conflict.

2021-05-19 09:24 UTC, fuxingloh commented on src/module.api/cache/poolpair.info.cache.ts
> +    }
I meant this:

https://github.com/DeFiCh/whale/blob/8af244c50118436567ce340f316f0bdb7b49efeb/src/module.api/cache/token.info.cache.ts#L27-L54

Because if you put everything together all the concerns get tied up into one function, harder to maintain in the long run. 

All mixed up, for one logical branch:
1. get: cache read, cache miss, **live read**, cache put, return put
1. get: cache read, cache hit, return hit

Live read is a heavy code branch that is part of another code logical branch that should be separated out. 

> https://en.wikipedia.org/wiki/Category_theory Categories represent abstractions of other mathematical concepts. Many areas of mathematics can be formalised by category theory as categories. Hence **category theory uses abstraction to make it possible to state and prove many intricate and subtle mathematical results in these fields** in a much simpler way.

2021-05-19 13:10 UTC, canonbrother commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +    const response = await client.poolpair.get('A-B')
use `get by id`.. solved.. =.=""

2021-05-19 15:59 UTC, canonbrother commented on src/module.api/poolpair.controller.ts
> +  async get (@Param('id') id: string): Promise<PoolPairInfoDto> {
bug: missing `@Param`    =.=""

2021-05-19 16:05 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +  async get (@Param('id') id: string): Promise<PoolPairInfoDto> {
Wow, hahaha

2021-05-19 16:21 UTC, fuxingloh requested changes

2021-05-19 16:21 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfoDto
I think there is still a better way to tackle this but it's beyond this scope. I guess we will look into it when we do https://github.com/DeFiCh/whale/issues/82

2021-05-19 16:21 UTC, fuxingloh commented on src/module.api/poolpair.controller.ts
> +  async get (@Param('id') id: string): Promise<PoolPairInfoDto> {
You could add a ParsetIntPipe for Param to validate path

2021-05-19 16:21 UTC, fuxingloh commented on src/module.api/poolpair.controller.spec.ts
> +    await expect(controller.get('999')).rejects.toThrow()
Should check the error type `NotFoundException`

2021-05-19 16:21 UTC, fuxingloh commented on packages/whale-api-client/src/api/poolpair.ts
> +}
should remove this first.

2021-05-19 16:21 UTC, fuxingloh commented on packages/whale-api-client/src/api/poolpair.ts
> +export interface PoolPairInfoDto {
For `packages/*` best to just name it `PoolPairData`.

1. packages are for public consumption hence, Dto is not a commonly used term outside of NestJS, only applicable within NestJS
2. `Info` is kind of fact conveying terminology, not good for conveying data states
3. We can't keep it as `PoolPair` or else it might conflict with the `export class PoolPair {`
3.  I use `PoolPairData` as data is a good word to represent the data and its state.
3. Data is also commonly understandable

2021-05-19 16:21 UTC, fuxingloh commented on packages/whale-api-client/__tests__/api/poolpair.test.ts
> +    await expect(client.poolpair.get('999')).rejects.toThrow()
should test error message

2021-05-20 03:37 UTC, canonbrother commented on src/module.api/poolpair.controller.ts
> +    return poolPairInfoDto
hmm... it would be considered call `fat` controller

2021-05-20 04:06 UTC, fuxingloh approved these changes

2021-05-20 04:07 UTC, merged